#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

## small hack to build all virtual machines, as long as whonix_build does not support --all.

build_all_error_handler() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $BASH_SOURCE: | caller: $(caller)${reset}
"
   exit 1
}

trap "build_all_error_handler" ERR

${1+"$@"} --build --install-to-root --tor-gateway

${1+"$@"} --build --install-to-root --tor-workstation

${1+"$@"} --build --install-to-root --tor-custom-workstation
