#!/bin/bash

#set -x

RecommendedTBBVersions="./tests/RecommendedTBBVersions"

source ../Whonix/packages/tb-updater/usr/lib/tbbversion_parser

tbbversion

echo "tbb_recommended_versions_list: $tbb_recommended_versions_list"

for tbb_version in $tbb_recommended_versions_list; do
   echo "tbb_version: $tbb_version"
done
