#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -f /usr/lib/pre.bsh ]; then
   source /usr/lib/pre.bsh
fi

## The following is required because *-postinst packages have been merged into
## the *-files packages. The *-postinst packages do not uninstall themselves,
## due to limitations in Whonix's build script (they are marked as manually
## installed and not depending on a bigger Whonix package, that could obsolete
## them. Also the old *-postinst scripts do not remove their dpkg diversion
## upon removal. That was not implemented at that point.

## Without this script, when running
##     dpkg-divert --add --rename --divert /usr/share/autostart/kmix_autostart.desktop.anondist-orig /usr/share/autostart/kmix_autostart.desktop
## We would see the following error message.
##     dpkg-divert: error: `diversion of /usr/share/autostart/kmix_autostart.desktop to
##     /usr/share/autostart/kmix_autostart.desktop.anondist-orig by whonix-workstation-files' clashes
##     with `local diversion of /usr/share/autostart/kmix_autostart.desktop to
##     /usr/share/autostart/kmix_autostart.desktop.anondist-orig'

sed -i -e 's/whonix-gateway-postinst/whonix-gateway-files/g' /var/lib/dpkg/diversions
sed -i -e 's/whonix-workstation-postinst/whonix-workstation-files/g' /var/lib/dpkg/diversions
