#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $0${1+"$@"}"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

change_partition_uuid() {
   trap "error_handler_unmount" ERR INT TERM

   ## If whonix_build is run with --fast2 switch.
   if [ "$WHONIX_BUILD_FAST2" = "1" ]; then
      echo "${bold}${cyan}INFO: run with --fast2 switch, skipping $0. ${reset}"
      exit 0
   fi

   sync

   if [ "$BARE_METAL" = "1" ]; then
      true "${cyan}INFO: Changing of partition uuid not implemented for bare metal.${reset}"
   else
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-raw
      ## Change partition uuid.
      true "${cyan}INFO: Changing of partition uuid...${reset}"
      tune2fs /dev/mapper/loop0p1 -U 26ada0c0-1165-4098-884d-aafd2220c2c6
      true "${cyan}INFO: Changed of partition uuid.${reset}"
      sync
      "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-raw
   fi

   sync
}

true "${bold}INFO: Currently running script: $0 ${1+"$@"}${reset}"
change_partition_uuid
