#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## This script needs to run before 20_sanity_checks, because debsums would
## otherwise output:
##     perl: warning: Please check that your locale settings:
##             LANGUAGE = "",
##             LC_ALL = (unset),
##             LANG = "en_GB.UTF-8"
##         are supported and installed on your system.
##     perl: warning: Falling back to the standard locale ("C").' = '' ']'
## Which is a confusing warning and considered an error in 20_sanity_checks.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

mkdir --parents "/usr/lib/whonix/"

if [ -f "/usr/lib/whonix/updated_locale" ]; then
   exit 0
fi

## Just doing this once, so users who changed from en_US.UTF-8 to something
## else won't always find them having their locale reset to en_US.UTF-8 each
## time there are updated Whonix debian packages.

locale-gen

update-locale LANG=en_US.UTF-8

touch "/usr/lib/whonix/updated_locale"
