#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

install-files-packages() {
   trap "errorhandlerunchrootunpreventunmount" ERR INT TERM

   if [ "$WHONIX_BUILD_USE_AUTO_LOCAL_SIGNING_KEY" = "1" ]; then
      if [ ! -f "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done ]; then
         error "${red}${bold}$BASH_SOURCE ERROR: "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done does not exist. Most likely build-steps.d/1200_create-debian-packages has not been run yet.${reset}"
      fi
   fi

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-raw
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/prevent-daemons-from-starting

   ## Deactivate mounting of /etc/resolv.conf inside chroot,
   ## because /etc/resolv.conf from whonix_gateway/whonix_workstation folder
   ## is going to be installed.
   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/chroot-raw

   unset WHONIX_CHROOT_MOUNT_RESOLV_CONF

   sync

   ## Sanity tests.
   $CHROOT $update_grub_bin -v
   $CHROOT sync

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/create-local-temp-apt-repo

   ## Debugging.
   $CHROOT apt-key finger

   ## Implemented in help-steps/pre.
   aptcachemaybeenable

   sync

   ## Reading apt repository containing snapshot.debian.org and local repository containing Whonix's packages.
   #$CHROOT apt-get $apt_sourcelist_empty $apt_sourceparts $apt_timeout_opts $apt_verify_opts -o APT::Get::List-Cleanup="0" update

   sync

   $CHROOT apt-get $apt_sourcelist_empty $apt_sourceparts $apt_timeout_opts --yes --no-install-recommends install whonix-shared-files

   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      $CHROOT apt-get $apt_sourcelist_empty $apt_sourceparts $apt_timeout_opts --yes install --no-install-recommends whonix-gateway-files
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      $CHROOT apt-get $apt_sourcelist_empty $apt_sourceparts $apt_timeout_opts --yes install --no-install-recommends whonix-workstation-files
   else
      bug "${red}${bold}ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!${reset}"
   fi

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/remove-local-temp-apt-repo

   ## Forget about local repository containing Whonix's packages.
   #$CHROOT apt-get --no-download --list-cleanup update

   $CHROOT sync
   sync

   ## Implemented in help-steps/pre.
   apt_cache_disable

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-raw
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-raw

   sync
}

true "${bold}${under}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
install-files-packages
benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}${under}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
