#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

verify_copied_files() {
   trap "error_handler_unmount" ERR INT TERM

   for i in $(find "$1"); do
      if [ -d "$i" ]; then
         continue
      fi
      if [ "$(basename "$i")" = ".directory" ]; then
         echo "${bold}${cyan}INFO: skipping to diff $i. ${reset}"
         continue
      fi
      local temp
      temp="${i#"$1"}"
      local chroot_file
      chroot_file="$CHROOT_FOLDER/$temp"
      echo "${cyan}INFO${reset}: Diffing "$i" with "$chroot_file"..."
      diff "$i" "$chroot_file"
   done
}

verify_copied_f() {
   trap "error_handler_unmount" ERR INT TERM

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-raw
   ## Setting +x because the for loops otherwise cause too much output.
   set +x

   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      verify_copied_files "$WHONIX_SOURCE_FOLDER/whonix_gateway/"
      verify_copied_files "$WHONIX_SOURCE_FOLDER/whonix_shared/"
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      verify_copied_files "$WHONIX_SOURCE_FOLDER/whonix_workstation/"
      verify_copied_files "$WHONIX_SOURCE_FOLDER/whonix_shared/"
   else
      bug "${red}${bold}ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!${reset}"
   fi

   set -x
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-raw
}

true "${bold}${under}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
verify_copied_f
benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}${under}INFO: End of: $BASH_SOURCE $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
