#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "Currently running script: $0 ${1+"$@"}"

TEMP_SCRIPTNAME="$0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

install-postinst-d-packages() {
   trap "error_handler_unchroot_unprevent_unmount" ERR INT TERM

   if [ "$WHONIX_BUILD_USE_AUTO_LOCAL_SIGNING_KEY" = "1" ]; then
      if [ ! -f "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done ]; then
         error "${red}${bold}$0 ERROR: "$WHONIX_LOCAL_SIGNING_KEY_FOLDER"/done does not exist. Most likely build-steps.d/1200_create-debian-packages has not been run yet.${reset}"
      fi
   fi

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-img
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/prevent-daemons-from-starting
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/chroot-img

   sync

   ## Sanity tests.
   $CHROOT $update_grub_bin -v
   $CHROOT sync

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/create-local-temp-apt-repo

   ## Debugging.
   $CHROOT apt-key finger

   ## Implemented in help-steps/pre.
   maybe_enable_apt_cache

   sync

   ## Reading apt repository containing snapshot.debian.org and local repository containing Whonix's packages.
   #$CHROOT apt-get $apt_dir_opts $apt_timeout_opts $apt_verify_opts -o APT::Get::List-Cleanup="0" update

   sync

   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      $CHROOT apt-get $apt_dir_opts $apt_timeout_opts --yes --no-install-recommends install whonix-gateway-postinst
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      $CHROOT apt-get $apt_dir_opts $apt_timeout_opts --yes --no-install-recommends install whonix-workstation-postinst
   else
      bug "${red}${bold}ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!${reset}"
   fi

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/remove-local-temp-apt-repo

   ## Forget about local repository containing Whonix's packages.
   #$CHROOT apt-get --no-download --list-cleanup update

   $CHROOT sync
   sync

   ## Implemented in help-steps/pre.
   disable_apt_cache

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-img
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-img

   sync
}

true "${bold}INFO: Currently running script: $0 ${1+"$@"}${reset}"
install-postinst-d-packages
true "${bold}INFO: End of: $0 No error detected.${reset}"
