#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source /usr/share/whonix/postinst.d/pre.bsh

## Check if user "rawdog" already exist.

ret="0"
id rawdog || { ret="$?" ; true; };

if [ ! "$ret" = "0" ]; then
   true 'INFO: Creating user "rawdog"...'
   ## setting password of user rawdog to changeme
   ##
   ## How this password was created:
   ## sudo apt-get install whois
   ## mkpasswd
   ## changeme
   ## Resulted in: aTayYxVyw5kDo
   useradd --password aTayYxVyw5kDo --user-group --create-home --shell /bin/bash rawdog
else
   true 'Not creating user "rawdog", because it rawdog already exists.'
fi
