#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      force_echo "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Enable apt-cacher-ng proxy.
export http_proxy="http://127.0.0.1:3142"

mkdir --parents "$EMPTY_DIR"

## Update Debian upstream package lists, so latest version of Tor, torsocks and obfsproxy gets known.
apt-get update \
   -o Dir::Etc::sourcelist="/etc/apt/sources.list" \
   -o Dir::Etc::sourceparts="$EMPTY_DIR" \
   -o APT::Get::List-Cleanup="0"

## Disable apt-cacher-ng proxy.
unset http_proxy
