#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -f /usr/lib/pre.bsh ]; then
   source /usr/lib/pre.bsh
fi

##################
## kgpg settings #
##################

## Now implemented in whonix_shared/usr/share/whonix/kde/share/config/kgpgrc
#sudo -u user kwriteconfig --file kgpgrc \
             #--group "General Options" \
             #--key "First run" \
             #--type bool \
             #false

## Now implemented in whonix_shared/usr/share/whonix/kde/share/config/kgpgrc
#sudo -u user kwriteconfig --file kgpgrc \
#             --group "Servers" \
#             --key "Server_List" \
#             --type string \
#             hkp://2eghzlv2wwcq7u7y.onion,hkp://keys.gnupg.net,hkp://pgp.dtype.org,hkp://search.keyserver.net,hkp://subkeys.pgp.net,hkp://wwwkeys.pgp.net,hkp://wwwkeys.pgp.net,hkp://wwwkeys.us.pgp.net

## Now implemented in whonix_shared/usr/share/whonix/kde/share/config/kgpgrc
#sudo -u user kwriteconfig --file kgpgrc \
             #--group "TipOfDay" \
             #--key "RunOnStart" \
             #--type bool \
             #false

#temp='$HOME/.gnupg/gpg.conf'

## Now implemented in whonix_shared/usr/share/whonix/kde/share/config/kgpgrc
#sudo -u user kwriteconfig --file kgpgrc \
             #--group "GPG Settings" \
             #--key gpg_config_path \
             #--type string \
             #$temp

###################
## kgpg tray icon #
###################

## Never worked.
#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
             #--group Containments --group 1 --group Applets --group 6 --group Configuration \
             #--key 'alwaysShown' \
             #--type string \
             #KGpg

#################
## Double Click #
#################

## Now implemented in whonix_shared/usr/share/whonix/kde/share/config/kdeglobals
#sudo -u user kwriteconfig --file kdeglobals \
             #--group KDE \
             #--key SingleClick \
             #--type bool \
             #false

#############################
## plasma-desktop-appletsrc #
#############################

## TODO: KDE

## Could be used to disable the clock. Would it be safe?
#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#            --group Containments --group 1 --group Applets --group 7 \
#             --key plugin \
#             --type string \
#            ""

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key dateStyle \
#             --type string \
#            0

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key defaultTimezone \
#             --type string \
#            UTC

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key showSeconds \
#             --type bool \
#            true

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key showTimezone \
#             --type bool \
#            true

#kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key timeZones \
#             --type string \
#            UTC

#sudo -u user kwriteconfig --file plasma-desktop-appletsrc \
#             --group Containments --group 1 --group Applets --group 7 --group Configuration \
#             --key timezone \
#             --type string \
#            UTC

#######
# END #
#######

## Only for developing/testing.
#sudo -u user kquitapp plasma-desktop
#sudo -u user sleep 1
#sudo -u user plasma-desktop

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
