#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $BASH_SOURCE)"
for skip_script in $SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      force_echo "INFO: Skipping $own_filename, because SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

command_v_return="0"
command -v update-command-not-found || { command_v_return="$?" ; true; };

if [ "$command_v_return" = "0" ]; then
   ## Just for convenience so the user will not be
   ## promoted "Please update-command-not-found.".
   ##
   ## This is problematic, because /var/cache/apt/pkgcache.bin and
   ## /var/cache/command-not-found/main.db are not deterministic. Either
   ## because the version from build 2 is newer than from build 1 or because
   ## the creation process of these files is not deterministic. Not researched.
   update-command-not-found
else
   true "INFO $BASH_SOURCE: update-command-not-found not installed, skipping update-command-not-found."
fi
