#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $BASH_SOURCE)"
for skip_script in $SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      force_echo "INFO: Skipping $own_filename, because SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Enable apt-cacher-ng proxy.
export http_proxy="http://127.0.0.1:3142"

## required for regeneration of /var/lib/xml-core folder

folder="/var/lib/whonix/initial-pkgs/xml-core"
rm -r -f "$folder"
mkdir --parents "$folder"

cd "$folder"

## Install 686 pae kernel.
apt-get $apt_sourcelist_empty $apt_sourceparts $apt_timeout_opts $apt_verify_opts download xml-core

## Disable apt-cacher-ng proxy.
unset http_proxy
