#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################
"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
for skip_script in $WHONIX_BUILD_SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      force_echo "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Installation of 486 kernel (in chroot-scripts-post.d 70_install_486_kernel)
## might have run update-grub (as part of its postinst script) and
## chroot-scripts-post.d 85_update_grub runs update-grub to let changes in
## /etc/default/grub take effect.
## grub has a bug to mess up /boot/grub/grub.cfg when run inside chroot
## (which will get fixed in grub 2.something).
## Therefore we restore a grub.cfg here, from which we made a backup
## (in chroot-scripts-post.d 30_backup_grub_cfg).
## (Originally fixed by grml-debootstrap.)
cp /boot/grub/grub.cfg.whonix-chroot-post /boot/grub/grub.cfg

sync
