#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Gets started by /usr/share/applications/gateway-firsttimesetup.desktop.

set -x

maximize_window() {
   if [ ! -f /usr/lib/msgcollector/msgwmctrl ]; then
      return 0
   fi
   source /usr/lib/msgcollector/msgwmctrl

   true "INFO: Getting own window title..."
   ## sets: own_window_title
   get_own_window_title
   ## Deactivate eventual trap from msgwmctrl.
   trap "" ERR
   if [ "$own_window_title" = "false" ]; then
      true "ERROR: Failed to find out own window title."
      return 0
   fi
   title="$own_window_title"

   true "INFO: Waiting for window title \"$title\" to appear..."
   ## sets: window_title_found
   output_wait_for_window "$title"
   ## Deactivate eventual trap from msgwmctrl.
   trap "" ERR
   if [ "$window_title_found" = "false" ]; then
      true "ERROR: window title \"$title\" did not appear."
      return 0
   fi

   true "INFO: Maximizing window title \"$title\"..."
   sleep 1 &
   wait "$!"
   wmctrl -b add,maximized_vert,maximized_horz -r "$title"
   true "INFO: Maximized window title \"$title\"."
   sleep 1 &
   wait "$!"
}

cat /etc/motd

maximize_window
sudo whonixsetup --x

true "INFO: Feel free to close this window."

sleep 86400
