#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Adds Tor stream isolation to apt-cacher-ng. Disabled by default.
##
## This file is supposed to be run by the /etc/init.d/apt-cacher-ng init script.
##
## (1) Change /etc/init.d/apt-cacher-ng
##        start-stop-daemon --start --chuid $USER --group $GROUP --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
##     to
##        start-stop-daemon --start --chuid $USER --group $GROUP --quiet --pidfile $PIDFILE --exec /usr/bin/apt-cacher-ng_uwt -- $DAEMON $DAEMON_OPTS
##
## (2) Deactivate apt-get uwt wrapper.
##        create a file /etc/whonix.d/20_user with
##        uwtwrapper_aptget="0"
##
## (3) Add to /etc/apt/apt.conf:
##        Acquire::http { Proxy "http://127.0.0.1:3142"; };

port="9104"

if [ -f "/usr/share/whonix/whonix_workstation" ]; then
   ip="192.168.0.10"
elif [ -f "/usr/share/whonix/whonix_gateway" ]; then
   ip="127.0.0.1"
else
   error "/usr/bin/apt-cacher-ng-uwt wrapper could not determine if this is Whonix-Workstation or Whonix-Gateway."
   error "Please report this bug!"
fi

/usr/bin/uwt -t 5 -i "$ip" -p "$port" $*
