#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

SCRIPTNAME="$(basename $0)"

## Not in use for Whonix-Workstation.
if [ -e /usr/share/whonix/whonix_workstation ]; then
   true
   exit 0
fi

root_check() {
   if [ "$(id -u)" != "0" ]; then
      echo "ERROR: $SCRIPTNAME must run as root."
      exit 1
   fi
}

process_background() {

   mkdir --parents /var/lib/whonix/

   BACKGROUND_PROCESSED="/var/lib/whonix/background.jpeg"

   cp /usr/share/whonix/mountainmist-orig.jpeg "$BACKGROUND_PROCESSED"

   ## Modify bottom.

   MSG='


Welcome to Whonix-Gateway! This is NOT a personal work station for your own private activities! So please do NOT use Whonix-Gateway for any purpose other than configuring Tor and
Whonix. The more you learn about Whonix and anonymity, the safer you can become. Reading Whonix documentation is recommended.

If your host has little RAM, you are advised to reduce Whonix-Gateway RAM to 128 MB. No graphical desktop environment will be started in that case.
A Whonix-Gateway without graphical desktop environment works as good as one with, it is just not that convenient. If you want, you can sometimes start a graphical desktop
environment and sometimes only a terminal by toggling how much RAM is available to Whonix-Gateway. Documentation about this feature: https://www.whonix.org/wiki/Desktop

If you want to change the keyboard layout from the default \"us\" to something else:
Start menu button -> Applications -> Settings -> System Settings -> input devices -> layout -> add yours and remove default one -> apply -> Done.

Default username: user
Default password: changeme


'

   convert "$BACKGROUND_PROCESSED" \
      -background Khaki label:"$MSG" \
      -gravity Center \
      -append "$BACKGROUND_PROCESSED"
}

root_check
process_background
