#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

WHONIX_BUILD_PARSED="1"
ROOT_CHECK="0"
VMNAME="internalrun"

source pre
source variables

cleanup_files() {
   trap "error_handler_general" ERR INT TERM

   set +x

   local result
   result="$(gawk '/^Package\:[[:space:]]*.*$$/ { match($$BASH_SOURCE, /^Package:[[:space:]]*(.*)$$/, m); print m[1]"*.deb" }' "$WHONIX_SOURCE_FOLDER/debian/control")"

   for dp in $result; do
      local cmd
      cmd="rm --force $WHONIX_SOURCE_FOLDER/../$dp"
      echo "$cmd"
      $cmd
   done

   local cmd

   cmd="rm --force $WHONIX_SOURCE_FOLDER/../$(gawk '/^Source\:[[:space:]]+.*$$/ { match($$BASH_SOURCE, /^Source:[[:space:]]+(.*)$$/, m); print m[1]"*.dsc" }' "$WHONIX_SOURCE_FOLDER/debian/control")"
   echo "$cmd"
   $cmd

   cmd="rm --force $WHONIX_SOURCE_FOLDER/../$(gawk '/^Source\:[[:space:]]+.*$$/ { match($$BASH_SOURCE, /^Source:[[:space:]]+(.*)$$/, m); print m[1]"*.changes" }' "$WHONIX_SOURCE_FOLDER/debian/control")"
   echo "$cmd"
   $cmd

   cmd="rm --force $WHONIX_SOURCE_FOLDER/../$(gawk '/^Source\:[[:space:]]+.*$$/ { match($$BASH_SOURCE, /^Source:[[:space:]]+(.*)$$/, m); print m[1]"*.tar.*" }' "$WHONIX_SOURCE_FOLDER/debian/control")"
   echo "$cmd"
   $cmd

   cmd="rm --force $WHONIX_SOURCE_FOLDER/../$(gawk '/^Source\:[[:space:]]+.*$$/ { match($$BASH_SOURCE, /^Source:[[:space:]]+(.*)$$/, m); print m[1]"*.build" }' "$WHONIX_SOURCE_FOLDER/debian/control")"
   echo "$cmd"
   $cmd

   set -x

   fakeroot "$WHONIX_SOURCE_FOLDER/debian/rules" clean

   rm --force "$WHONIX_SOURCE_FOLDER/debian/changelog"
}

true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
cleanup_files
benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
