#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

trap "error_handler_general" ERR INT TERM

error_handler_copy-into-raw() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
Unmounting raw...
"

   "$WHONIX_SOURCE_FOLDER"/help-steps/unmount-raw

   : echo "
{red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
"

   exit 1
}

copy_into_vm_image_whonix_gateway() {
   trap "error_handler_copy-into-raw" ERR INT TERM

   copy_backup_shared
   copy_into_shared

   copy_backup_gateway
   copy_into_gateway

   ## Ensure changes get written before unmounting.
   sync
}

copy_into_vm_image_whonix_workstation() {
   trap "error_handler_copy-into-raw" ERR INT TERM

   copy_backup_shared
   copy_into_shared

   copy_backup_workstation
   copy_into_workstation

   ## Ensure changes get written before unmounting.
   sync
}

copy_backup_shared() {
   trap "error_handler_copy-into-raw" ERR INT TERM

   ## Better no backup of localtime.
   #cp --no-clobber "$CHROOT_FOLDER"/etc/localtime "$CHROOT_FOLDER"/etc/localtime.backup

   ## Better no backup of dbusmachineid.
   #cp --no-clobber "$CHROOT_FOLDER"/var/lib/dbus/machine-id "$CHROOT_FOLDER"/var/lib/dbus/machine-id.backup

   touch "$CHROOT_FOLDER"/etc/motd
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/motd "$CHROOT_FOLDER"/etc/motd.backup || true

   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/apt/sources.list "$CHROOT_FOLDER"/etc/apt/sources.list.backup
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/hosts "$CHROOT_FOLDER"/etc/hosts.backup || true
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/issue "$CHROOT_FOLDER"/etc/issue.backup || true
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/inittab "$CHROOT_FOLDER"/etc/inittab.backup || true
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/network/interfaces "$CHROOT_FOLDER"/etc/network/interfaces.backup
}

copy_into_shared() {
   trap "error_handler_copy-into-raw" ERR INT TERM

   ## Copy
   rsync --verbose --perms --recursive --checksum "$WHONIX_SOURCE_FOLDER"/whonix_shared/ "$CHROOT_FOLDER"/
}

copy_backup_gateway() {
   trap "error_handler_copy-into-raw" ERR INT TERM

   ## Backup torrc inside VM before replacing it with Whonix version.
   cp --no-clobber "$CHROOT_FOLDER"/etc/tor/torrc "$CHROOT_FOLDER"/etc/tor/torrc.backup
}

copy_into_gateway() {
   trap "error_handler_copy-into-raw" ERR INT TERM

   ## Copy
   rsync --verbose --perms --recursive --checksum "$WHONIX_SOURCE_FOLDER"/whonix_gateway/ "$CHROOT_FOLDER"/
}

copy_backup_workstation() {
   trap "error_handler_copy-into-raw" ERR INT TERM

   ## /etc/polipo/config
   ## not installing polipo by default
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/whonix_workstation/etc/polipo/config "$CHROOT_FOLDER"/etc/polipo/config.backup || true

   ## /etc/kde4/kdm/kdmrc
   ## Overriding with true because it's only for kde autologin for the case kde does not get installed in custom builds.
   cp --no-clobber --recursive --preserve "$CHROOT_FOLDER"/etc/kde4/kdm/kdmrc "$CHROOT_FOLDER"/etc/kde4/kdm/kdmrc.backup || true
}

copy_into_workstation() {
   trap "error_handler_copy-into-raw" ERR INT TERM

   ## /etc/resolv.conf
   ## We do not need chattr +i for Whonix-W resolv.conf, because
   ## DHCP is never used and resolvconf was uninstalled.

   ## Copy
   rsync --verbose --perms --recursive --checksum "$WHONIX_SOURCE_FOLDER"/whonix_workstation/ "$CHROOT_FOLDER"/
}

true "${bold}INFO: Currently running script: $0 ${1+"$@"}${reset}"

true "${cyan}NOTE: The $0 script will not automatically replace files with the .whonix extension with their corresponding files without the .whonix extension. For example, /etc/tor/torrc.whonix will not automatically replace /etc/tor/torrc.${reset}"

sleep 3

"$WHONIX_SOURCE_FOLDER"/help-steps/mount-raw

if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
   copy_into_vm_image_whonix_gateway
elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
   copy_into_vm_image_whonix_workstation
else
   bug "${red}${bold}ERROR${reset}: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!"
fi

"$WHONIX_SOURCE_FOLDER"/help-steps/unmount-raw

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
