#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

whonixdesktop_wait_seconds="$1"

desktop_sigterm() {
   #echo "$scriptname INFO: SIGTERM revived!"
   exit 1
}

trap "desktop_sigterm" SIGTERM

sleep_exit_code="0"
sleep "$whonixdesktop_wait_seconds" &
wait "$!" || { sleep_exit_code="$?" ; true; };

exit 0
