#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

## NOTE:
## /usr/share/whonix/postinst.d/70_legacy prevents this script from getting run
## on older versions not supporting the verifiable builds feature.

error_handler() {
   ## Debugging.
   true "WARNING: exited with non-zero exit code: $?"
}

trap "error_handler" ERR

## {{{ variables

DPKG_MAINTSCRIPT_PACKAGE_BACKUP="$DPKG_MAINTSCRIPT_PACKAGE"
DPKG_RUNNING_VERSION_BACKUP="$DPKG_RUNNING_VERSION"
DPKG_ADMINDIR_BACKUP="$DPKG_ADMINDIR"
DPKG_NO_TSTP_BACKUP="$DPKG_NO_TSTP"
DPKG_MAINTSCRIPT_ARCH_BACKUP="$DPKG_MAINTSCRIPT_ARCH"

DPKG_RUNNING_VERSION="$(dpkg-query --show --showformat='${Version}' "dpkg")"
export DPKG_RUNNING_VERSION

export DPKG_ADMINDIR="/var/lib/dpkg"
export DPKG_NO_TSTP="yes"

## }}}

maybe_run() {
   trap "error_handler" ERR

   local script basename_script package
   shopt -s nullglob dotglob

   for script in $1.preinst; do
      basename_script="$(basename "$script")"
      ## Example basename_script:
      ## libc6:i386.preinst
      package="$(echo "$basename_script" | tr ":" " " | awk '{print $1}')"
      ## Example package:
      ## libc6
      export DPKG_MAINTSCRIPT_PACKAGE="$package"
      export DPKG_MAINTSCRIPT_NAME="preinst"
      ## TODO: export DPKG_MAINTSCRIPT_ARCH="?"
      if [ ! -e "$script" ]; then
         true "INFO: $script does not exist."
      elif [ ! -x "$script" ]; then
         true "INFO: $script not executable."
      else
         true "INFO: Running... "$script" install"
         ## Example:
         ## /var/lib/dpkg/info/fontconfig.preinst install
         "$script" install
      fi
   done

   unset script basename_script package DPKG_MAINTSCRIPT_PACKAGE

   for script in $1.postinst; do
      basename_script="$(basename "$script")"
      ## Example basename_script:
      ## libc6:i386.postinst
      package="$(echo "$basename_script" | tr ":" " " | awk '{print $1}')"
      ## Example package:
      ## libc6
      export DPKG_MAINTSCRIPT_PACKAGE="$package"
      export DPKG_MAINTSCRIPT_NAME="postinst"
      ## TODO: export DPKG_MAINTSCRIPT_ARCH="?"
      if [ ! -e "$script" ]; then
         true "INFO: $script does not exist."
      elif [ ! -x "$script" ]; then
         true "INFO: $script not executable."
      else
         true "INFO: Running... "$script" install"
         ## Example:
         ## /var/lib/dpkg/info/fontconfig.postinst configure
         "$script" configure
      fi
   done

   unset script basename_script package DPKG_MAINTSCRIPT_PACKAGE

   shopt -u nullglob dotglob
}

if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
else
    true "INFO: Script running as root."
fi

## non-deterministic [1]
## /var/cache/fontconfig folder
## does not exist /var/lib/dpkg/info/fontconfig-config
maybe_run "/var/lib/dpkg/info/fontconfig-config"

## non-deterministic [2]
## /var/cache/ldconfig/aux-cache file
maybe_run "/var/lib/dpkg/info/libc6*"

## non-deterministic [3]
## /var/cache/man folder
maybe_run "/var/lib/dpkg/info/man-db"

## non-deterministic [4]
## /var/lib/xml-core folder
## /etc/xml/catalog
## /etc/xml/catalog.old
## /etc/xml/xml-core.xml
## /etc/xml/xml-core.xml.old
maybe_run "/var/lib/dpkg/info/xml-core"

## non-deterministic [6]
## /var/lib/sgml-base/supercatalog
## /var/lib/sgml-base/supercatalog.old
maybe_run "/var/lib/dpkg/info/sgml-base"

## non-deterministic [5]
## /etc/xml/sgml-data
## /etc/xml/sgml-data.old
maybe_run "/var/lib/dpkg/info/sgml-data"

## non-deterministic [7]
## /etc/xml/docbook-xml.xml
## /etc/xml/docbook-xml.xml.old
maybe_run "/var/lib/dpkg/info/docbook-xml"

## non-deterministic [14]
## /etc/xml/docbook-xsl.xml
## /var/lib/xml-core/docbook-xsl
maybe_run "/var/lib/dpkg/info/docbook-xsl"

## non-deterministic [8]
## /usr/share/info/dir file
maybe_run "/var/lib/dpkg/info/install-info"

## non-deterministic [9]
## /usr/lib/*/gdk-pixbuf*/*/loaders.cache file
## ex: /usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
maybe_run "/var/lib/dpkg/info/libgdk-pixbuf*"

## non-deterministic [10]
## /usr/lib/i386-linux-gnu/gio/modules/giomodule.cache
## TODO: fix dpkg-trigger error, remove || true
maybe_run "/var/lib/dpkg/info/libglib*" || true

## non-deterministic [11]
## /usr/lib/i386-linux-gnu/*/*/immodules.cache
## /usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules.cache
## /usr/lib/i386-linux-gnu/gtk-3.0/3.0.0/immodules.cache
maybe_run "/var/lib/dpkg/info/libgtk*"

## non-deterministic [12]
## some /usr/lib/pymodules/python2.7/**/__init__.pyc
## does not exist: /var/lib/dpkg/info/python-support.prerm remove
maybe_run "/var/lib/dpkg/info/python-support"

## non-deterministic [13]
## /var/lib/gconf/defaults/%gconf-tree.xml
maybe_run "/var/lib/dpkg/info/gconf2-common"

## non-deterministic [14]
## /etc/init.d/.depend.boot
## /etc/init.d/.depend.start
## /etc/init.d/.depend.stop
if [ -x /sbin/insserv ]; then
   /sbin/insserv --showall
   /sbin/insserv --verbose
fi

## non-deterministic [15]
## /var/lib/urandom/random-seed

## non-deterministic [16]
## /etc/blkid.tab
maybe_run "/var/lib/dpkg/info/linux-base"

## non-deterministic [17]
## /etc/apt/trustdb.gpg
## Thanks to:
## https://unix.stackexchange.com/questions/110500/how-to-regenerate-etc-apt-trustdb-gpg-on-debian
## This is no longer required for Debian Jessie?
apt-key update

dpkg --configure -a

## exit 0 would not be required, but that makes it easier to check the last
## command in the log using a script.
exit 0

install_initial_packages() {
   trap "error_handler" ERR

   shopt -s nullglob dotglob

   for file_name in "/var/lib/whonix/initial-packages/"*; do
      ## Example file_name:
      ## /var/lib/whonix/initial-packages/nano_2.2.6-1+b1_i386.deb
      file_basename="$(basename "$file_name")"
      ## Example file_name:
      ## nano_2.2.6-1+b1_i386.deb
      package="$(echo "$file_basename" | tr "_" " " | awk '{print $1}')"
      ## Example package:
      ## nano
      dpkg_status="$(dpkg-query --show --showformat='${db:Status-Abbrev}' "$package")"
      ## Example dpkg_status:
      ## ii
      status_second_char="${dpkg_status:1:1}"
      ## Example status_second_char:
      ## i
      if [ "$status_second_char" = "i" ]; then
         ## Installed. Reinstall...
         true "INFO: Reinstalling $package ($file_name)..."
         dpkg --install "$file_name"
      else
         ## Not installed. Skipping.
         true "INFO: $package ($file_name) not installed, skipping."
      fi
   done

   shopt -u nullglob dotglob
}

## Deactivated for now. Let's see if we can substitute that we dpkg.
#install_initial_packages

## {{{ dpkg-reconfigure

#cp --preserve --verbose /usr/share/whonix/policy-rc.d /usr/sbin/policy-rc.d

#dpkg-reconfigure --force --all

#rm --verbose --force /usr/sbin/policy-rc.d

## }}}
