#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "${bold}${red}$BASH_SOURCE ERROR:${reset} BASH_COMMAND: $BASH_COMMAND"
   exit 1
}

trap "error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..

cd help-steps

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"

export ROOT_CHECK="0"
export VMNAME="internalrun"

source pre
source variables

make_debian_upstream_tarball() {
   trap "error_handler_general" ERR INT TERM

   ## The -n switch for gzip is required to produce a reproducible tarball.

   sudo -E -u "$user_name" \
         git archive \
            --format=tar HEAD \
            | gzip -n > "$WHONIX_SOURCE_PARENTDIR/whonix_${anon_dist_build_version}.orig.tar.gz"

   sync
}

true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
make_debian_upstream_tarball
benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
