#! /bin/bash
### BEGIN INIT INFO
# Provides:          timesyncd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Network Time Synchronization Status Boot Notifier
# Description:       Network Time Synchronization Status Boot Notifier
#
### END INIT INFO

# Author: Patrick Schleizer <adrelanos@riseup.net>

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

# Do NOT "set -e"

#set -x

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="timesyncd"
NAME=timesyncd
DAEMON=/usr/bin/timesync
DAEMON_ARGS="--autostart"
#PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

mkdir -p /var/run/whonix/whonixcheck/
chown --recursive user:user /var/run/whonix/whonixcheck/
chmod --recursive o+w /var/run/whonix/whonixcheck/
chmod --recursive g+w /var/run/whonix/whonixcheck/

mkdir -p /var/lib/whonix/whonixcheck/
chown --recursive user:user /var/lib/whonix/whonixcheck/
chmod --recursive o+w /var/lib/whonix/whonixcheck/
chmod --recursive g+w /var/lib/whonix/whonixcheck/

#
# Function that starts the daemon/service
#
do_start()
{
   do_stop

   #Debugging:
   ## --nosleep --nochecklastrun --verbose

   sudo -u user /usr/lib/whonix/delay $DAEMON $DAEMON_ARGS &

   return 0
}

#
# Function that stops the daemon/service
#
do_stop()
{
   killall timesync 2>/dev/null

   rm -f /var/run/whonix/whonixcheck/timesync_waiting
   rm -f /var/run/whonix/whonixcheck/timesync_done
   rm -f /var/run/whonix/whonixcheck/timesync_running

   return 0
}

do_status()
{
   if [ -f /var/run/whonix/whonixcheck/timesync_done ]; then
      return 0
   else
      return 1
   fi
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
	do_status || exit $?
	;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
