#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## news_v1
## - just a single clearsigned file on
##   http://sourceforge.net/projects/whonix/files/news/whonix_news.asc/download

## news_v0 ?
## - just a single clearsigned file on
##   http://whonix.sourceforge.net/whonix_news.asc

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/variables

whonix_news_gpg_sign_with_options="--sign-with 9C131AD3713AAEEF"

mkdir --parents "$WHONIX_BINARY"

## Reading ./release/whonix_news, substitute the $WHONIX_BUILD_WHONIX_VERSION variable in ./release/whonix_news
## with the actual WHONIX_BUILD_WHONIX_VERSION and storing it as ../whonix_binary/whonix_news.
##
## Thanks to:
## http://superuser.com/questions/235738/how-do-i-substitute-environment-variables-when-i-ouput-a-file

eval echo "\"$(cat <<EOF_$RANDOM
$(<"$whonix_dev_meta_files_folder/release/whonix_news")
EOF_$RANDOM
)\"" > "$WHONIX_BINARY/whonix_news"

cat "$WHONIX_BINARY/whonix_news"

rm --force "$WHONIX_BINARY/whonix_news.asc"

gpg $whonix_news_gpg_sign_with_options --clearsign "$WHONIX_BINARY/whonix_news"

cat "$WHONIX_BINARY/whonix_news.asc"

gpg --verify "$WHONIX_BINARY/whonix_news.asc"

sleep 10

rsync \
   --partial \
   --progress \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/whonix_news.asc" \
   adrelanos,whonix@frs.sourceforge.net:/home/frs/project/whonix/news/

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
