#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

kill_old_instances() {
   trap "error_handler" ERR

   return 0

   local me
   me="$$"

   ## Using --exact to prevent getting results for help scripts such
   ## as whonixcheck_hourly.
   local pids
   pids="$(pgrep --exact "$SCRIPTNAME")" || true

   for pid in $(echo $pids); do
      if [ "$pid" -ne "$me" ]; then
         local MSG
         MSG="$(date) | killing: "$pid" ... aux: $(ps aux | grep "$pid")"
         output "--info" "$MSG" "debug"
         kill -9 "$pid" || true
      else
         local MSG
         MSG="$(date) | not killing me "$pid" .. aux: $(ps aux | grep "$pid")"
         true "$MSG"
         output "--info" "$MSG" "debug"
      fi
   done
}
