#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler() {
   echo "
#############################################################
## postinst script: ERROR detected. Please report this bug! #
## scriptname: $0
## BASH_COMMAND: $BASH_COMMAND
#############################################################
"

   exit 1
}

trap "error_handler" ERR

own_filename="$(basename $0)"
case $WHONIX_BUILD_SKIP_SCRIPTS in
   *$own_filename*) true "INFO: Skipping $own_filename, because WHONIX_BUILD_SKIP_SCRIPTS includes it."
                    exit 0
                    ;;
esac

true "Adding timesanitycheck init script..."
update-rc.d timesanitycheck defaults
