#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

for file in $(find "./old"); do

   if [ -d "$file" ]; then
      continue
   fi

   basename_file="$(basename "$file")"
   true "basename_file: $basename_file"
   file_extension="${basename_file##*.}"

   echo "$file... ($file_extension)"

   if [ "$file_extension" = "gz" ]; then
      echo "Skipping $file."
      continue
   fi
   if [ "$file_extension" = "build" ]; then
      echo "Skipping $file."
      continue
   fi

   echo "debfiff... $file"

   debdiff "$file" "./new/$basename_file"

   #sleep 10

done
