#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/variables

[ -n "$version" ] || version="$anon_dist_build_version"

cd "$WHONIX_BINARY"

if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
   maybe_add_libvirt_network_xml_file="$(basename "$libvirt_target_network_file")"
   if [ ! -r "$maybe_add_libvirt_network_xml_file" ]; then
      error "$maybe_add_libvirt_network_xml_file not readable"
   fi
else
   maybe_add_libvirt_network_xml_file=""
fi

if [ ! -r "$(basename "$libvirt_target_kvm_file")" ]; then
   error "$(basename "$libvirt_target_kvm_file") is not readable!"
fi
if [ ! -r "$(basename "$libvirt_target_qemu_newer_archs_file")" ]; then
   error "$(basename "$libvirt_target_qemu_newer_archs_file") is not readable!"
fi
if [ ! -r "$(basename "$binary_image_qcow2")" ]; then
   error "$(basename "$binary_image_qcow2") is not readable!"
fi

rm --force "$(basename $libvirt_target_xz_archive)"

## Not using `gzip`, because it cannot handle sparse files:
## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=535987
#pv "$WHONIX_BINARY/Whonix-Gateway-$version.qcow2" | gzip -n - > "$WHONIX_BINARY/Whonix-Gateway-$version.libvirt.tar.gz"
#pv "$WHONIX_BINARY/Whonix-Workstation-$version.qcow2" | gzip -n - > "$WHONIX_BINARY/Whonix-Workstation-$version.libvirt.tar.gz"

## Using `tar` with `--xz` and `--mtime="2014-05-06 00:00:00"`:
## - will result in a deterministic archive. We do not have deterministic
##   images yet in the first place (but at least verifiable ones), but
##   hopefully some day. Does not hurt to already use tar options that do
##   not add unnecessary non-deterministic contents.
## Not using tar --verbose:
## - slows down tar too much.

## TODO: add progress meter (using `pv`?)

tar \
   --create \
   --sparse \
   --xz \
   --mtime="2014-05-06 00:00:00" \
   --directory="$WHONIX_BINARY" \
   --file "$(basename $libvirt_target_xz_archive)" \
   "$(basename "$libvirt_target_kvm_file")" \
   "$(basename "$libvirt_target_qemu_newer_archs_file")" \
   "$(basename "$binary_image_qcow2")" \
   $maybe_add_libvirt_network_xml_file

sync

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
