#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

version="$whonix_build_closest_git_tag"

## Not using `gzip`, because it cannot handle sparse files:
## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=535987
#pv "$WHONIX_BINARY/Whonix-Gateway-$version.qcow2" | gzip -n - > "$WHONIX_BINARY/Whonix-Gateway-$version.qcow2.tar.gz"
#pv "$WHONIX_BINARY/Whonix-Workstation-$version.qcow2" | gzip -n - > "$WHONIX_BINARY/Whonix-Workstation-$version.qcow2.tar.gz"

## Using `tar` with `--xz` and `--mtime="2014-05-06 00:00:00"`:
## - will result in a deterministic archive. We do not have deterministic
##   images yet in the first place (but at least verifiable ones), but
##   hopefully some day. Does not hurt to already use tar options that do
##   not add unnecessary non-deterministic contents.
## Not using tar --verbose:
## - slows down tar too much.

## TODO: add progress meter (using `pv`?)

tar \
   --create \
   --sparse \
   --xz \
   --mtime="2014-05-06 00:00:00" \
   --directory="$WHONIX_BINARY" \
   --file "$WHONIX_BINARY/Whonix-Gateway-$version.qcow2.xz" \
   "Whonix-Gateway-$version.qcow2"

sync

tar \
   --create \
   --sparse \
   --xz \
   --mtime="2014-05-06 00:00:00" \
   --directory="$WHONIX_BINARY" \
   --file "$WHONIX_BINARY/Whonix-Workstation-$version.qcow2.xz" \
   "Whonix-Workstation-$version.qcow2"

sync

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE No error detected. (benchmark: $benchmark_took_time)${reset}"
