#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "Currently running script: $0 ${1+"$@"}"
set -o pipefail

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/variables

version="$whonix_build_closest_git_tag"

mkdir --parents "$WHONIX_BINARY"

cd "/mnt/shared/"

cp "sha512sum" "$WHONIX_BINARY/"
sync

cp "sha1sum" "$WHONIX_BINARY/"
sync

cp "Whonix-Gateway-$version.ova" "$WHONIX_BINARY/"
cp "Whonix-Gateway-$version.qcow2" "$WHONIX_BINARY/"
sync

cp "Whonix-Workstation-$version.ova" "$WHONIX_BINARY/"
cp "Whonix-Workstation-$version.qcow2" "$WHONIX_BINARY/"
sync

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
