#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

mkdir --parents "$WHONIX_BINARY"

cd "/mnt/shared/"

## {{ hash sum

## md5sum is sufficient here, because it gets only used for an integrity check,
## to see if copying around on a local hdd succeeded.

cp "md5sum" "$WHONIX_BINARY/"
sync

## }} hash sum

for file_name in $whonix_build_files_list; do
   sudo -u "$user_name" cp "$file_name" "$WHONIX_BINARY/"
done

sync
