#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/variables

#sudo mount -t vboxsf -o uid=1000,gid=1000 shared /mnt/shared

## Sanity test.
ls -ls "/mnt/shared/" >/dev/null

cd "$WHONIX_BINARY"

## md5sum is sufficient here, because it gets only used for an integrity check,
## to see if copying around on a local hdd succeeded.

#rm --force "md5sum"

if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
   ## Using basename for using relative pathsin sha512sum file.
   base_name_file_name="$(basename "$binary_image_ova")"
   ## Create md5sum to compare with sourceforge.
   sudo -u "$user_name" md5sum "$base_name_file_name" | sudo -u "$user_name" tee -a "md5sum"
   sudo -u "$user_name" cp "$binary_image_ova" "/mnt/shared/"
elif [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
   for file_name in $whonix_build_qcow2_file_list; do
      true "file_name: $file_name"
      base_name_file_name="$(basename "$file_name")"
      sudo -u "$user_name" md5sum "$base_name_file_name" | sudo -u "$user_name" tee -a "md5sum"
      sudo -u "$user_name" cp "$file_name" "/mnt/shared/"
   done
else
   error "Neither --target virtualbox nor --target qcow2 chosen."
fi

## Debugging.
sudo -u "$user_name" cat "md5sum"

sudo -u "$user_name" cp "md5sum" "/mnt/shared/"

sync

benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
