#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/variables

#sudo mount -t vboxsf -o uid=1000,gid=1000 shared /mnt/shared

version="$whonix_build_closest_git_tag"

cd "$WHONIX_BINARY"

rm --force sha512sum
rm --force sha1sum

## Create sha512sum sum to ensure copying was done without bit flip.
sha512sum *.ova >> sha512sum
sha512sum *.qcow2 >> sha512sum
sync

## Debugging.
cat sha512sum

## Create sha1sum to compare with sourceforge.
sha1sum *.ova >> sha1sum
sha1sum *.qcow2 >> sha1sum
sync

## Debugging.
cat sha1sum

cp "sha512sum" "/mnt/shared/"
sync

cp "sha1sum" "/mnt/shared/"
sync

cp "Whonix-Gateway-$version.ova" "/mnt/shared/"
cp "Whonix-Gateway-$version.qcow2" "/mnt/shared/"
sync

cp "Whonix-Workstation-$version.ova" "/mnt/shared/"
cp "Whonix-Workstation-$version.qcow2" "/mnt/shared/"
sync

true "${bold}INFO: End of: $0 No error detected.${reset}"
