#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

#sudo mount -t vboxsf -o uid=1000,gid=1000 shared /mnt/shared

## Sanity test.
ls -ls "/mnt/shared/" >/dev/null

version="$whonix_build_closest_git_tag"

cd "$WHONIX_BINARY"

## {{ hash sum

## md5sum is sufficient here, because it gets only used for an integrity check,
## to see if copying around on a local hdd succeeded.

rm --force "md5sum"

## Create md5sum to compare with sourceforge.
md5sum "Whonix-Gateway-$version.ova" >> "md5sum"
md5sum "Whonix-Gateway-$version.qcow2" >> "md5sum"
md5sum "Whonix-Workstation-$version.ova" >> "md5sum"
md5sum "Whonix-Workstation-$version.qcow2" >> "md5sum"
sync

## Debugging.
cat "md5sum"

cp "md5sum" "/mnt/shared/"
sync

## }}

cp "Whonix-Gateway-$version.ova" "/mnt/shared/"
cp "Whonix-Gateway-$version.qcow2" "/mnt/shared/"
sync

cp "Whonix-Workstation-$version.ova" "/mnt/shared/"
cp "Whonix-Workstation-$version.qcow2" "/mnt/shared/"
sync

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE No error detected. (benchmark: $benchmark_took_time)${reset}"
