#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/variables

cd "$WHONIX_BINARY"

rm --force "$sha_five_hundredth_twelve_hash_file"

## Create sha512sum.
## Using `basename` so we end up with relative paths in sha512sum file.

if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
   sha512sum "$(basename "$binary_image_ova")" >> "$sha_five_hundredth_twelve_hash_file"
   #sha512sum "$(basename "$binary_image_ova_signature")" >> "$sha_five_hundredth_twelve_hash_file"
   #sha512sum "$(basename "$binary_image_ova_torrent")" >> "$sha_five_hundredth_twelve_hash_file"
   #sha512sum "$(basename "$binary_image_ova_torrent_signature")" >> "$sha_five_hundredth_twelve_hash_file"
elif [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
   sha512sum "$(basename "$libvirt_target_xz_archive")" >> "$sha_five_hundredth_twelve_hash_file"
   #sha512sum "$(basename "$libvirt_target_xz_archive_signature")" >> "$sha_five_hundredth_twelve_hash_file"
   #sha512sum "$(basename "$libvirt_target_xz_archive_torrent")" >> "$sha_five_hundredth_twelve_hash_file"
   #sha512sum "$(basename "$libvirt_target_xz_archive_torrent_signature")" >> "$sha_five_hundredth_twelve_hash_file"
else
   error "Neither --target virtualbox nor --target qcow2 chosen."
fi

sync

## Sanity test.
sha512sum --check "$sha_five_hundredth_twelve_hash_file"

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
