#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefile

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

version="$whonix_build_closest_git_tag"

## Thanks to:
## https://github.com/moba/createtortorrents/blob/master/createtorrents.sh

#TRACKERS="udp://tracker.openbittorrent.com:80/announce,udp://tracker.publicbt.com:80/announce,http://tracker.openbittorrent.com:80/announce,http://tracker.publicbt.com:80/announce,udp://tracker.ccc.de/announce"

TRACKERS="http://announce.torrentsmd.com:6969/announce"

sudo -E -u "$user_name" mkdir --parents "$WHONIX_BINARY/torrent-$version"
chown --recursive "$user_name:$user_name" "$WHONIX_BINARY/torrent-$version"

## Not well supported by BitTorrent clients.
## Multi file webseeds do not work
##     https://trac.transmissionbt.com/ticket/4437
## (fixed upstream, but takes a while to propagate to Debian stable)
#sudo -E -u "$user_name" mktorrent \
#   --verbose \
#   --announce="$TRACKERS" \
#   --web-seed "http://webseed.whonix.org:8008/Whonix-Gateway-7.ova" \
#   --web-seed "http://webseed.whonix.org:8008/Whonix-Workstation-7.ova" \
#   ~/7

## CoralCDN:
## .8008.nyud.net can no longer be appended to http://webseed.whonix.org:8008,
## because CoralCDN appear to no longer support files greater than 50 MB.

sudo -E -u "$user_name" mktorrent \
   --verbose \
   --announce="$TRACKERS" \
   --web-seed "http://webseed.whonix.org:8008/$version/Whonix-Gateway-$version.ova" \
   -o "$WHONIX_BINARY/torrent-$version/Whonix-Gateway-$version.ova.torrent" \
   "$WHONIX_BINARY/Whonix-Gateway-$version.ova"

sudo -E -u "$user_name" mktorrent \
   --verbose \
   --announce="$TRACKERS" \
   --web-seed "http://webseed.whonix.org:8008/$version/Whonix-Workstation-$version.ova" \
   -o "$WHONIX_BINARY/torrent-$version/Whonix-Workstation-$version.ova.torrent" \
   "$WHONIX_BINARY/Whonix-Workstation-$version.ova"

sudo -E -u "$user_name" mktorrent \
   --verbose \
   --announce="$TRACKERS" \
   --web-seed "http://webseed.whonix.org:8008/$version/Whonix-Custom-Workstation-$version.ova" \
   -o "$WHONIX_BINARY/torrent-$version/Whonix-Custom-Workstation-$version.ova.torrent" \
   "$WHONIX_BINARY/Whonix-Custom-Workstation-$version.ova"

## Working.
#echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org:8008/Whonix-Gateway-7.ova");' "$2")"
#echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org:8008/Whonix-Workstation-7.ova");' "$2")"

## Not working.
#echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org:8008/Whonix-Gateway-7.ova");' "$2")"
#echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org:8008/Whonix-Workstation-7.ova");' "$2")"

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE No error detected. (benchmark: $benchmark_took_time)${reset}"
