#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/variables

sudo -u "$user_name" \
   mkdir --parents "$WHONIX_BINARY"

sudo -u "$user_name" \
   cp "$whonix_dev_meta_files_folder/release/download_folder_README" "$WHONIX_BINARY/"

sudo -u "$user_name" \
   rm --force "$WHONIX_BINARY/download_folder_README.asc"

sudo -u "$user_name" \
   gpg --clearsign "$WHONIX_BINARY/download_folder_README"

sudo -u "$user_name" \
   cat "$WHONIX_BINARY/download_folder_README.asc"

sudo -u "$user_name" \
   gpg --verify "$WHONIX_BINARY/download_folder_README.asc"

sleep 10

sudo -u "$user_name" \
   rsync \
      --partial \
      --progress \
      --verbose \
      --rsh ssh \
      "$WHONIX_BINARY/download_folder_README.asc" \
      "adrelanos,whonix@frs.sourceforge.net:/home/frs/project/whonix/whonix-$WHONIX_BUILD_WHONIX_VERSION/README"

true "${bold}INFO: End of: $0 No error detected.${reset}"
