#!/bin/bash

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Thanks to:
## http://stackoverflow.com/a/2154277

recurse() {
 for i in "$1"/*;do
    if [ -d "$i" ];then
        #echo "dir: $i"
        recurse "$i"
    elif [ -f "$i" ]; then
        echo "$i"
    fi
 done
}

recurse ~/derivative-maker
