#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "Currently running script: $0 ${1+"$@"}"
set -o pipefile

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

## Thanks to:
## https://github.com/moba/createtortorrents/blob/master/createtorrents.sh

#TRACKERS="udp://tracker.openbittorrent.com:80/announce,udp://tracker.publicbt.com:80/announce,http://tracker.openbittorrent.com:80/announce,http://tracker.publicbt.com:80/announce,udp://tracker.ccc.de/announce"

TRACKERS="http://announce.torrentsmd.com:6969/announce"

sudo -E -u "$user_name" mkdir --parents "$WHONIX_BINARY/torrent-$whonix_build_closest_git_tag"
chown --recursive "$user_name:$user_name" "$WHONIX_BINARY/torrent-$whonix_build_closest_git_tag"

## Not well supported by BitTorrent clients.
## Multi file webseeds do not work
##     https://trac.transmissionbt.com/ticket/4437
## (fixed upstream, but takes a while to propagate to Debian stable)
#sudo -E -u "$user_name" mktorrent \
#   --verbose \
#   --announce="$TRACKERS" \
#   --web-seed "http://webseed.whonix.org.8008.nyud.net/Whonix-Gateway-7.ova" \
#   --web-seed "http://webseed.whonix.org.8008.nyud.net/Whonix-Workstation-7.ova" \
#   ~/7

sudo -E -u "$user_name" mktorrent \
   --verbose \
   --announce="$TRACKERS" \
   --web-seed "http://webseed.whonix.org.8008.nyud.net/Whonix-Gateway-$whonix_build_closest_git_tag.ova" \
   -o "$WHONIX_BINARY/torrent-$whonix_build_closest_git_tag/Whonix-Gateway-$whonix_build_closest_git_tag.ova.torrent" \
   "$WHONIX_BINARY/Whonix-Gateway-$whonix_build_closest_git_tag.ova"

sudo -E -u "$user_name" mktorrent \
   --verbose \
   --announce="$TRACKERS" \
   --web-seed "http://webseed.whonix.org.8008.nyud.net/Whonix-Workstation-$whonix_build_closest_git_tag.ova" \
   -o "$WHONIX_BINARY/torrent-$whonix_build_closest_git_tag/Whonix-Workstation-$whonix_build_closest_git_tag.ova.torrent" \
   "$WHONIX_BINARY/Whonix-Workstation-$whonix_build_closest_git_tag.ova"

## Working.
#echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org:8008/Whonix-Gateway-7.ova");' "$2")"
#echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org:8008/Whonix-Workstation-7.ova");' "$2")"

## Not working.
#echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org.8008.nyud.net/Whonix-Gateway-7.ova");' "$2")"
#echo "$(perl -MURI::Escape -e 'print uri_escape("http://webseed.whonix.org.8008.nyud.net/Whonix-Workstation-7.ova");' "$2")"

true "${bold}INFO: End of: $0 No error detected.${reset}"
