#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
mydir_backup="$MYDIR"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

cd "$mydir_backup"

#../debug-steps/reprepro-wrapper copymatched buster-proposed-updates buster-testers "*"
../debug-steps/reprepro-wrapper copymatched bullseye-proposed-updates bullseye-testers "*"

true "${cyan}INFO: Done. Migrated testers repository to proposed-updates repository. Do not forget to upload it.${reset}"
