#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

## disable cmd line parser, since not needed
export dist_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
mydir_backup="$MYDIR"
cd "$MYDIR"

source ../../../../help-steps/pre
source ../../../../help-steps/colors
source ../../../../help-steps/variables

cd "$mydir_backup"

for derivative_name_item in $derivative_name_list ; do
   export derivative_name_item

   #../debug-steps/reprepro-wrapper copymatched buster-testers buster-developers "*"
   ../debug-steps/reprepro-wrapper copymatched bullseye-testers bullseye-developers "*"

   true "${cyan}INFO: Done. Migrated developers repository to testers repository. Do not forget to upload it.${reset}"
done
