#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
mydir_backup="$MYDIR"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/variables

cd "$mydir_backup"

true "${bold}${red}INFO: Are you sure you want to do this? Stable repository is only for users of Whonix 8. If you want to continue, please press enter. Otherwise ctrl + c.${reset}"
read temp

../debug-steps/reprepro-wrapper copymatched stable testers "*"

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
true "${cyan}INFO: Done. Migrated developers repository to testers repository. Do not forget to upload it.${reset}"
