#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
mydir_backup="$MYDIR"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

cd "$mydir_backup"

../debug-steps/reprepro-wrapper copymatched stretch-testers stretch-developers "*"

true "${cyan}INFO: Done. Migrated stretch-developers repository to stretch-testers repository. Do not forget to upload it.${reset}"
