#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

cd "$WHONIX_BINARY"

[ -n "$version" ] || version="$anon_dist_build_version"

mirror_ips="
192.34.63.51
109.230.212.53
151.80.190.129
109.230.212.54
192.99.131.144
86.59.119.84
144.76.14.145
212.110.161.69
178.217.184.32
"

set +x
for mirror_ip in $mirror_ips; do
   curl_cmd="curl --silent -H 'Host: mirror.whonix.de' -k http://$mirror_ip/whonixdevelopermetafiles/internal/news_v4/whonix_news.tar.xz.asc"
   echo "$curl_cmd"

   if [ "$curl_result_old" = "" ]; then
      curl_result_old="$(eval $curl_cmd)"
      hash_old="$(echo "$curl_result_old" | sha512sum)"
      #echo "$curl_result_old"
      echo "${green}FIRST :${reset} $mirror_ip"
      echo "${green}FIRST :${reset} $hash_old"
      continue
   fi
   curl_result_new="$(eval $curl_cmd)"
   hash_new="$(echo "$curl_result_new" | sha512sum)"
   #echo "$curl_result_new"

   if [ "$hash_old" = "$hash_new" ]; then
      echo "${green}OK     :${reset} $mirror_ip"
      echo "${green}OK     :${reset} $hash_new"
      continue
   fi
   echo "${red}FAILED${reset}: $mirror_ip"
   echo "${red}FAILED${reset}: $hash_new"
done
set -x
