#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## disable cmd line parser, since not needed
export dist_build_one_parsed="1"
export VMNAME="internalrun"

cd "$MYDIR"

source ../../../../help-steps/pre
source ../../../../help-steps/colors
source ../../../../help-steps/variables

cd "$binary_build_folder_dist"

## https://www.whonix.org/wiki/Dev/Mirrors

## dig mirror.whonix.de ANY +noall +answer

mirror_ips="
192.34.63.51
151.80.190.129
109.230.212.53
109.230.212.54
86.59.119.84
144.76.14.145
212.110.161.69
178.217.184.32
"

set +x
for mirror_ip in $mirror_ips; do
   curl_cmd=""
   echo ""

   echo "curl --output /tmp/x --max-time 10 --silent -H 'Host: mirror.whonix.de' -k http://$mirror_ip/developer-meta-files/internal/news_v4/whonix_news.tar.xz.asc"
   rm -f /tmp/x
   curl --output /tmp/x --max-time 10 --silent -H 'Host: mirror.whonix.de' -k http://$mirror_ip/developer-meta-files/internal/news_v4/whonix_news.tar.xz.asc || true
   touch /tmp/x

   if [ "$hash_old" = "" ]; then
      hash_old="$(cat "/tmp/x" | sha512sum)"
      echo "${green}FIRST :${reset} $mirror_ip"
      echo "${green}FIRST :${reset} $hash_old"
      continue
   fi

   hash_new="$(cat "/tmp/x" | sha512sum)"

   if [ "$hash_old" = "$hash_new" ]; then
      echo "${green}OK     :${reset} $mirror_ip"
      echo "${green}OK     :${reset} $hash_new"
      continue
   fi
   echo "${red}FAILED${reset}: $mirror_ip"
   echo "${red}FAILED${reset}: $hash_new"
done
set -x
