#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Whonix News v4
## A deterministic tarball on
## http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news_v4/whonix_news.tar.xz/download
## and a detached armored OpenPGP signature on
## http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news_v4/whonix_news.tar.xz.asc/download

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

if [ "$(id -u)" = "0" ]; then
   echo "${red}${bold}ERROR: Do not run this script as root!${reset}"
   exit 1
fi

"$whonix_dev_meta_files_folder/release/compress_libvirt"

"$whonix_dev_meta_files_folder/release/create_torrent"

"$whonix_dev_meta_files_folder/release/create_hashes"

"$whonix_dev_meta_files_folder/release/sign_images"

"$whonix_dev_meta_files_folder/release/upload_torrent"

"$whonix_dev_meta_files_folder/release/upload_signatures"

"$whonix_dev_meta_files_folder/release/upload_images"

benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
