#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

if [ "$(id -u)" = "0" ]; then
   echo "${red}${bold}ERROR: Do not run this script as root!${reset}"
   exit 1
fi

timestamp=$(date --utc +"%Y%m%d%H%M")

mkdir --parents "$binary_build_folder_dist/qubes-build-commands"
file_path="$binary_build_folder_dist/qubes-build-commands"

echo "Build-template r4.0 whonix-gateway-14 $timestamp" > "$file_path/r4.0_whonix-gateway-14.txt"
gpg --yes --clearsign "$file_path/r4.0_whonix-gateway-14.txt"
rm -f "$file_path/r4.0_whonix-gateway-14.txt"
gpg --verify "$file_path/r4.0_whonix-gateway-14.txt.asc"

echo "Build-template r4.0 whonix-workstation-14 $timestamp" > "$file_path/r4.0_whonix-workstation-14.txt"
gpg --yes --clearsign "$file_path/r4.0_whonix-workstation-14.txt"
rm -f "$file_path/r4.0_whonix-workstation-14.txt"
gpg --verify "$file_path/r4.0_whonix-workstation-14.txt.asc"

true "Press any key to continue."
read temp

cat "$file_path/r4.0_whonix-gateway-14.txt.asc"
true "Press any key to continue."
read temp

cat "$file_path/r4.0_whonix-workstation-14.txt.asc"
true "Press any key to continue."
read temp

true END
