#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

## Debugging.
"$WHONIX_SOURCE_HELP_STEPS_FOLDER/gpg_test_sign"

"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export jessie
"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export jessie-proposed-updates
"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export testers
"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export stretch
"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export stretch-testers
"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export stretch-developers

true "${cyan}INFO: Done. Refreshed repository. OpenPGP Resigned and updated valid-until field. Do not forget to upload the refreshed repository. ${reset}"
