#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $0${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export stable
"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export testers
"$whonix_dev_meta_files_folder/debug-steps/reprepro-wrapper" --export=changed export developers

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"

true "${cyan}INFO: Done. Refreshed repository. OpenPGP Resigned and updated valid-until field. Do not forget to upload the refreshed repository. ${reset}"
