#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/variables

cd "$WHONIX_BINARY"

## Debugging.
"$WHONIX_SOURCE_HELP_STEPS_FOLDER/gpg_test_sign"

## {{ hash sum

## md5sum is sufficient here, because it gets only used for an integrity check,
## to see if copying around on a local hdd succeeded.

#md5sum --check md5sum

## }}

## Create detached signatures.
if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
   gpg --detach-sign --armor --yes "$binary_image_ova"
   #gpg --detach-sign --armor --yes "$binary_image_ova_torrent"
fi

if [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
   gpg --detach-sign --armor --yes "$libvirt_target_xz_archive"
   #gpg --detach-sign --armor --yes "$libvirt_target_xz_archive_torrent"
fi
#gpg --detach-sign --armor --yes "$sha_five_hundredth_twelve_hash_file"

## Verify, that signing worked.
if [ "$WHONIX_BUILD_VIRTUALBOX" = "true" ]; then
   gpg --verify "$binary_image_ova_signature"
   #gpg --verify "$binary_image_ova_torrent_signature"
fi

if [ "$WHONIX_BUILD_QCOW2" = "true" ]; then
   gpg --verify "$libvirt_target_xz_archive_signature"
   #gpg --verify "$libvirt_target_xz_archive_torrent_signature"
fi
#gpg --verify "$sha_five_hundredth_twelve_hash_file_signature"

sync

benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
