#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

version="$whonix_build_closest_git_tag"

cd "$WHONIX_BINARY"

echo "test" > "$WHONIX_BINARY/test_sign_file"
gpg --detach-sign --armor --yes "$WHONIX_BINARY/test_sign_file"
gpg --verify "$WHONIX_BINARY/test_sign_file.asc"
rm "$WHONIX_BINARY/test_sign_file"
rm "$WHONIX_BINARY/test_sign_file.asc"

## {{ hash sum

## md5sum is sufficient here, because it gets only used for an integrity check,
## to see if copying around on a local hdd succeeded.

md5sum --check md5sum

## }}

## Create detached signatures.
gpg --detach-sign --armor --yes "Whonix-Gateway-$version.ova"
gpg --detach-sign --armor --yes "Whonix-Gateway-$version.libvirt.xz"
gpg --detach-sign --armor --yes "Whonix-Workstation-$version.ova"
gpg --detach-sign --armor --yes "Whonix-Workstation-$version.libvirt.xz"
gpg --detach-sign --armor --yes "Whonix-Custom-Workstation-$version.ova"
gpg --detach-sign --armor --yes "Whonix-Custom-Workstation-$version.libvirt.xz"

## Verify, that signing worked.
gpg --verify "Whonix-Gateway-$version.ova.asc"
gpg --verify "Whonix-Gateway-$version.libvirt.xz.asc"
gpg --verify "Whonix-Workstation-$version.ova.asc"
gpg --verify "Whonix-Workstation-$version.libvirt.xz.asc"
gpg --verify "Whonix-Custom-Workstation-$version.ova.asc"
gpg --verify "Whonix-Custom-Workstation-$version.libvirt.xz.asc"

## Create sha512sum.
rm --force sha512sum
sha512sum "Whonix-Gateway-$version.ova" >> sha512sum
sha512sum "Whonix-Gateway-$version.ova.asc" >> sha512sum
sha512sum "Whonix-Gateway-$version.libvirt.xz" >> sha512sum
sha512sum "Whonix-Gateway-$version.libvirt.xz.asc" >> sha512sum
sha512sum "Whonix-Workstation-$version.ova" >> sha512sum
sha512sum "Whonix-Workstation-$version.ova.asc" >> sha512sum
sha512sum "Whonix-Workstation-$version.libvirt.xz" >> sha512sum
sha512sum "Whonix-Workstation-$version.libvirt.xz.asc" >> sha512sum
sha512sum "Whonix-Custom-Workstation-$version.ova" >> sha512sum
sha512sum "Whonix-Custom-Workstation-$version.ova.asc" >> sha512sum
sha512sum "Whonix-Custom-Workstation-$version.libvirt.xz" >> sha512sum
sha512sum "Whonix-Custom-Workstation-$version.libvirt.xz.asc" >> sha512sum

sync

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE No error detected. (benchmark: $benchmark_took_time)${reset}"
