#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $0${1+"$@"}"
set -o pipefail

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

version="$whonix_build_closest_git_tag"

cd "$WHONIX_BINARY"

## {{ hash sum

## md5sum is sufficient here, because it gets only used for an integrity check,
## to see if copying around on a local hdd succeeded.

md5sum --check md5sum

## }}

## Create detached signatures.
gpg --detach-sign --armor --yes "Whonix-Gateway-$version.ova"
gpg --detach-sign --armor --yes "Whonix-Gateway-$version.qcow2"
gpg --detach-sign --armor --yes "Whonix-Workstation-$version.ova"
gpg --detach-sign --armor --yes "Whonix-Workstation-$version.qcow2"

## Verify, that signing worked.
gpg --verify "Whonix-Gateway-$version.ova.asc"
gpg --verify "Whonix-Gateway-$version.qcow2.asc"
gpg --verify "Whonix-Workstation-$version.ova.asc"
gpg --verify "Whonix-Workstation-$version.qcow2.asc"

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
