#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

[ -n "$version" ] || version="$anon_dist_build_version"

#sf_user="adrelanos"
#sf_project="testprojectwh"
#sf_project="whonix"
#sf_project="whonixdevelopermetafiles"
#server="$sf_user,$sf_project@frs.sourceforge.net:/home/frs/project/$sf_project/$version/"

server="root@rsync.whonix.org:/var/rsync/$version/"

if [ "$server" = "" ]; then
   error "Variable server is empty."
fi

ls -la "$WHONIX_BINARY/"*".sha512sums"
ls -la "$WHONIX_BINARY/"*".ova"
ls -la "$WHONIX_BINARY/"*".libvirt.xz"
ls -la "$WHONIX_BINARY/"*".asc"

true "${cyan}INFO: Press any enter to continue.${reset}"
read temp

## Test.
rsync \
   --dry-run \
   $rsync_opts \
   "$WHONIX_BINARY/"*".sha512sums" \
   "$WHONIX_BINARY/"*".ova" \
   "$WHONIX_BINARY/"*".libvirt.xz" \
   "$WHONIX_BINARY/"*".asc" \
   "$server"

true "${cyan}INFO: Press any enter to continue.${reset}"
read temp

attempts_counter="0"
attempts_max="10"

while true; do
   attempts_counter="$(( $attempts_counter + 1 ))"

   rsync_exit_code="0"
   rsync \
      $rsync_opts \
      "$WHONIX_BINARY/"*".sha512sums" \
      "$WHONIX_BINARY/"*".ova" \
      "$WHONIX_BINARY/"*".libvirt.xz" \
      "$WHONIX_BINARY/"*".asc" \
      "$server" \
      || { rsync_exit_code="$?" ; true; };

   if [ "$rsync_exit_code" = "0" ]; then
      break
   fi

   if [ "$attempts_counter" -ge "$attempts_max" ]; then
      msg="${bold}${red}INFO: Upload failed.${reset}"
      true "$msg"
      error "$msg"
   fi

   sleep 10

done

benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
