#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Whonix News v2
## Many small OpenPGP clearsigned files on
## http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news/

set -x
true "INFO: Currently running script: $0${1+"$@"}"
set -o pipefail

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

whonix_news_gpg_sign_with_options="--sign-with 9C131AD3713AAEEF"

mkdir --parents "$WHONIX_BINARY/news"

## Reading ./release/whonix_news, substitute the $WHONIX_BUILD_WHONIX_VERSION variable in ./release/whonix_news
## with the actual WHONIX_BUILD_WHONIX_VERSION and storing it as ../whonix_binary/whonix_news.
##
## Thanks to:
## http://superuser.com/questions/235738/how-do-i-substitute-environment-variables-when-i-ouput-a-file

for i in "$whonix_dev_meta_files_folder/release/news/"*; do
   if [ -f "$i" ]; then
      ## If the last character is a ~, ignore that file,
      ## because it was created by some editor,
      ## which creates backup files.
      if [ "${i: -1}" = "~" ]; then
         continue
      fi
   fi

   filename="$(basename "$i")"

   cp "$i" "$WHONIX_BINARY/news/$filename"

   cat "$WHONIX_BINARY/news/$filename"

   rm --force "$WHONIX_BINARY/news/$filename.asc"

   gpg $whonix_news_gpg_sign_with_options --clearsign "$WHONIX_BINARY/news/$filename"

   rm "$WHONIX_BINARY/news/$filename"

   cat "$WHONIX_BINARY/news/$filename.asc"

   gpg --verify "$WHONIX_BINARY/news/$filename.asc"

done

rm --force "$WHONIX_BINARY/news/.directory"

ls -la "$WHONIX_BINARY/news/"

true "INFO $0: Please press enter to continue with --dry-run."

read temp

true "INFO $0: Running with --dry-run..."
rsync \
   --dry-run \
   --partial \
   --progress \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/news/"* \
   adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news/

true "INFO $0: Please press enter to continue to upload."

read temp

true "INFO $0: Uploading..."
rsync \
   --partial \
   --progress \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/news/"* \
   adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news/

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
