#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/variables

if [ "$(id -u)" = "0" ]; then
   true "ERROR: Do not run this as root!"
   exit 1
fi

#project="testprojectwh"
#project="whonix"
project="whonixdevelopermetafiles"

shopt -s globstar

true "${cyan}INFO $BASH_SOURCE: Showing dists...${reset}"

set +x

for file in "$WHONIX_BINARY/aptrepo_remote/dists/"**; do
   if [ -d "$file" ]; then
      continue
   fi
   echo "$file"
done
unset file

echo "${cyan}INFO $BASH_SOURCE: Please press enter to continue showing pool.${reset}"
read temp

echo "${cyan}INFO $BASH_SOURCE: Showing pool...${reset}"

for file in "$WHONIX_BINARY/aptrepo_remote/pool/"**; do
   if [ -d "$file" ]; then
      continue
   fi
   echo "$file"
done
unset file

set -x

true "${cyan}INFO $BASH_SOURCE: Please press enter to continue with dists with --dry-run.${reset}"
read temp

true "${cyan}INFO $BASH_SOURCE: Running dists with --dry-run...${reset}"
rsync \
   --dry-run \
   $rsync_opts \
   --recursive \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/dists/"* \
   "adrelanos,$project@frs.sourceforge.net:/home/frs/project/$project/internal/dists/"

true "${cyan}INFO $BASH_SOURCE: Please press enter to continue with pool with --dry-run.${reset}"
read temp

true "${cyan}INFO $BASH_SOURCE: Running pool with --dry-run...${reset}"
rsync \
   --dry-run \
   $rsync_opts \
   --recursive \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/pool/"* \
   "adrelanos,$project@frs.sourceforge.net:/home/frs/project/$project/internal/pool/"

true "${cyan}INFO $BASH_SOURCE: Please press enter to continue to uploading dists and pool.${reset}"
read temp

true "${cyan}INFO $BASH_SOURCE: Uploading dists...${reset}"
rsync \
   $rsync_opts \
   --recursive \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/dists/"* \
   "adrelanos,$project@frs.sourceforge.net:/home/frs/project/$project/internal/dists/"

true "${cyan}INFO $BASH_SOURCE: Uploading pool...${reset}"
rsync \
   $rsync_opts \
   --recursive \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/pool/"* \
   "adrelanos,$project@frs.sourceforge.net:/home/frs/project/$project/internal/pool/"

benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
