#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

[ -n "$version" ] || version="$anon_dist_build_version"

ls -la ~/"whonix_binary/"*".asc"
ls -la ~/"whonix_binary/"*".sha512sums"

true "${cyan}INFO: Press enter to continue.${reset}"
read temp

## Test.
rsync \
   --dry-run \
   $rsync_opts \
   --rsh='ssh' \
   ~/"whonix_binary/"*".asc" \
   ~/"whonix_binary/"*".sha512sums" \
   "adrelanos@whonix.org:/home/adrelanos/download/$version/"

true "${cyan}INFO: Press enter to continue.${reset}"
read temp

rsync \
   $rsync_opts \
   --rsh='ssh' \
   ~/"whonix_binary/"*".asc" \
   ~/"whonix_binary/"*".sha512sums" \
   "adrelanos@whonix.org:/home/adrelanos/download/$version/"
