#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "Currently running script: $0 ${1+"$@"}"
set -o pipefail

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/variables

#project="testprojectwh"
#project="whonix"
project="whonixdevelopermetafiles"

shopt -s globstar

true "INFO $0: Showing dists..."

set +x

for file in "$WHONIX_BINARY/aptrepo_remote/dists/"**; do
   if [ -d "$file" ]; then
      continue
   fi
   echo "$file"
done
unset file

echo "INFO $0: Please press enter to continue showing pool."
read temp

echo "INFO $0: Showing pool..."

for file in "$WHONIX_BINARY/aptrepo_remote/pool/"**; do
   if [ -d "$file" ]; then
      continue
   fi
   echo "$file"
done
unset file

set -x

true "INFO $0: Please press enter to continue with dists with --dry-run."
read temp

true "INFO $0: Running dists with --dry-run..."
rsync \
   --dry-run \
   --partial \
   --progress \
   --recursive \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/dists/"* \
   adrelanos,"$project"@frs.sourceforge.net:/home/frs/project/"$project"/internal/dists/

true "INFO $0: Please press enter to continue with pool with --dry-run."
read temp

true "INFO $0: Running pool with --dry-run..."
rsync \
   --dry-run \
   --partial \
   --progress \
   --recursive \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/pool/"* \
   adrelanos,"$project"@frs.sourceforge.net:/home/frs/project/"$project"/internal/pool/


true "INFO $0: Please press enter to continue to uploading dists and pool."
read temp

true "INFO $0: Uploading dists..."
rsync \
   --partial \
   --progress \
   --recursive \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/dists/"* \
   adrelanos,"$project"@frs.sourceforge.net:/home/frs/project/"$project"/internal/dists/

true "INFO $0: Uploading pool..."
rsync \
   --partial \
   --progress \
   --recursive \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/pool/"* \
   adrelanos,"$project"@frs.sourceforge.net:/home/frs/project/"$project"/internal/pool/

true "${bold}INFO: End of: $0 No error detected.${reset}"
