#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

if [ "$(id -u)" = "0" ]; then
   true "ERROR: Do not run this as root!"
   exit 1
fi

cat "$WHONIX_BINARY/canary/canary.txt"

true "${cyan}INFO $BASH_SOURCE: Please press enter to continue canary github.${reset}"
read temp

cp "$WHONIX_BINARY/canary/canary.txt.asc" ~/sourcesown/canary/
cp "$WHONIX_BINARY/canary/canary.txt" ~/sourcesown/canary/
cp "$WHONIX_BINARY/canary/canary.txt.clearsign.asc" ~/sourcesown/canary/
cp "$WHONIX_BINARY/canary/canary.txt.sig" ~/sourcesown/canary/
cp "$WHONIX_BINARY/canary/canary.txt.embed.sig" ~/sourcesown/canary/

pushd ~/sourcesown/canary/
git add -A
git commit -a -m "update canary"
git push origin master
git push adre master
popd

true "${cyan}INFO $BASH_SOURCE: Please press enter to continue canary --dry-run.${reset}"
read temp
true "${cyan}INFO $BASH_SOURCE: Running pool with --dry-run...${reset}"
rsync \
   --dry-run \
   $rsync_opts \
   --recursive \
   --rsh ssh \
   "$WHONIX_BINARY/canary/canary.txt.asc" \
   "$WHONIX_BINARY/canary/canary.txt" \
   "$WHONIX_BINARY/canary/canary.txt.clearsign.asc" \
   "$WHONIX_BINARY/canary/canary.txt.sig" \
   "$WHONIX_BINARY/canary/canary.txt.embed.sig" \
   "root@whonix.org:/var/rsync/developer-meta-files/canary"

true "${cyan}INFO $BASH_SOURCE: Please press enter to continue canary.${reset}"
read temp

true "${cyan}INFO $BASH_SOURCE: Uploading canary...${reset}"
rsync \
   $rsync_opts \
   --recursive \
   --rsh ssh \
   "$WHONIX_BINARY/canary/canary.txt.asc" \
   "$WHONIX_BINARY/canary/canary.txt" \
   "$WHONIX_BINARY/canary/canary.txt.clearsign.asc" \
   "$WHONIX_BINARY/canary/canary.txt.sig" \
   "$WHONIX_BINARY/canary/canary.txt.embed.sig" \
   "root@whonix.org:/var/rsync/developer-meta-files/canary"
