#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Whonix News v3
## A tarball on
## http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news_v3/whonix_news.tar.gz/download
## and a detached armored OpenPGP signature on
## http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news_v3/whonix_news.tar.gz.asc/download

set -x
true "Currently running script: $0 ${1+"$@"}"
set -o pipefail

error_handler() {
   echo "FAILED!"
   exit 1
}

trap "error_handler" ERR

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/variables

if [ "$(id -u)" = "0" ]; then
   echo "${red}${bold}ERROR: Do not run this script as root!${reset}"
   exit 1
fi

rm --force --recursive "$WHONIX_BINARY/news_v3_temp"
rm --force --recursive "$WHONIX_BINARY/news_v3"
mkdir --parents "$WHONIX_BINARY/news_v3_temp"
mkdir --parents "$WHONIX_BINARY/news_v3"

for i in "$whonix_dev_meta_files_folder/release/news/"*; do
   if [ -f "$i" ]; then
      ## If the last character is a ~, ignore that file,
      ## because it was created by some editor,
      ## which creates backup files.
      if [ "${i: -1}" = "~" ]; then
         continue
      fi
   fi

   filename="$(basename "$i")"

   ## --preserve to keep timestamps, to make it deterministic.
   cp --preserve "$i" "$WHONIX_BINARY/news_v3_temp/$filename"

   ## Debugging.
   cat "$WHONIX_BINARY/news_v3_temp/$filename"

done

rm --force "$WHONIX_BINARY/news_v3_temp/.directory"

sync

## Non-deterministic.
tar -zcvpf "$WHONIX_BINARY/news_v3/whonix_news.tar.gz" -C "$WHONIX_BINARY/news_v3_temp" .

## Deterministic, but we can't use this, because it would break Whonix News v3.
## This has to be implemented in Whonix News v4.
#find "$WHONIX_BINARY/news_v3_temp/"* -print0 | sort -z | tar --no-recursion --null -Jcvf "$WHONIX_BINARY/news_v3/whonix_news.tar.gz" -T -

sync

gpg --detach-sign --armor --yes "$WHONIX_BINARY/news_v3/whonix_news.tar.gz"
sync
gpg --verify "$WHONIX_BINARY/news_v3/whonix_news.tar.gz.asc"

true "INFO $0: Please press enter to continue with --dry-run."

read temp

true "INFO $0: Running with --dry-run..."
rsync \
   --dry-run \
   --partial \
   --progress \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/news_v3/whonix_news.tar.gz.asc" \
   "$WHONIX_BINARY/news_v3/whonix_news.tar.gz" \
   "adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news_v3/"

true "INFO $0: Please press enter to continue to upload."

read temp

true "INFO $0: Uploading..."
rsync \
   --partial \
   --progress \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/news_v3/whonix_news.tar.gz.asc" \
   "$WHONIX_BINARY/news_v3/whonix_news.tar.gz" \
   "adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news_v3/"

true "${bold}INFO: End of: $0 No error detected.${reset}"
