#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"
set -o pipefail

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/variables

[ -n "$version" ] || version="$anon_dist_build_version"

ls -la ~/"whonix_binary/torrent-$version/"*

true "${cyan}INFO: Press enter to continue.${reset}"
read temp

## Test.
rsync \
   --dry-run \
   $rsync_opts \
   --rsh='ssh -p54485' \
   ~/"whonix_binary/torrent-$version/"* \
   "adrelanos@whonix.org:/home/adrelanos/download/$version-torrent/"

true "${cyan}INFO: Press enter to continue.${reset}"
read temp

rsync \
   $rsync_opts \
   --rsh='ssh -p54485' \
   ~/"whonix_binary/torrent-$version/"* \
   "adrelanos@whonix.org:/home/adrelanos/download/$version-torrent/"

benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
