#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

sudo -u "$user_name" \
   mkdir --parents "$WHONIX_BINARY"

sudo -u "$user_name" \
   cp "$whonix_dev_meta_files_folder/release/readme/news_folder_README" "$WHONIX_BINARY/"

sudo -u "$user_name" \
   rm --force "$WHONIX_BINARY/news_folder_README.asc"

sudo -u "$user_name" \
   gpg --clearsign "$WHONIX_BINARY/news_folder_README"

sudo -u "$user_name" \
   cat "$WHONIX_BINARY/news_folder_README.asc"

sudo -u "$user_name" \
   gpg --verify "$WHONIX_BINARY/news_folder_README.asc"

sleep 10

sudo -u "$user_name" \
   rsync \
      $rsync_opts \
      --rsh ssh \
      "$WHONIX_BINARY/news_folder_README.asc" \
      adrelanos,whonix@frs.sourceforge.net:/home/frs/project/whonix/news/README
