#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
true "INFO: Currently running script: $0${1+"$@"}"
set -o pipefail

## disable cmd line parser, since not needed
export WHONIX_BUILD_PARSED="1"
export VMNAME="internalrun"
ROOT_CHECK="0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

#project="testprojectwh"
#project="whonix"
project="whonixdevelopermetafiles"

shopt -s globstar

true "${cyan}INFO $0: Showing dists...${reset}"

set +x

for file in "$WHONIX_BINARY/aptrepo_remote/dists/"**; do
   if [ -d "$file" ]; then
      continue
   fi
   echo "$file"
done
unset file

echo "INFO $0: Please press enter to continue showing pool."
read temp

echo "INFO $0: Showing pool..."

for file in "$WHONIX_BINARY/aptrepo_remote/pool/"**; do
   if [ -d "$file" ]; then
      continue
   fi
   echo "$file"
done
unset file

set -x

true "${cyan}INFO $0: Please press enter to continue with dists with --dry-run.${reset}"
read temp

true "${cyan}INFO $0: Running dists with --dry-run...${reset}"
rsync \
   --dry-run \
   --partial \
   --progress \
   --recursive \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/dists/"* \
   adrelanos,"$project"@frs.sourceforge.net:/home/frs/project/"$project"/internal/dists/

true "${cyan}INFO $0: Please press enter to continue with pool with --dry-run.${reset}"
read temp

true "${cyan}INFO $0: Running pool with --dry-run...${reset}"
rsync \
   --dry-run \
   --partial \
   --progress \
   --recursive \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/pool/"* \
   adrelanos,"$project"@frs.sourceforge.net:/home/frs/project/"$project"/internal/pool/


true "${cyan}INFO $0: Please press enter to continue to uploading dists and pool.${reset}"
read temp

true "${cyan}INFO $0: Uploading dists...${reset}"
rsync \
   --partial \
   --progress \
   --recursive \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/dists/"* \
   adrelanos,"$project"@frs.sourceforge.net:/home/frs/project/"$project"/internal/dists/

true "${cyan}INFO $0: Uploading pool...${reset}"
rsync \
   --partial \
   --progress \
   --recursive \
   --verbose \
   --rsh ssh \
   "$WHONIX_BINARY/aptrepo_remote/pool/"* \
   adrelanos,"$project"@frs.sourceforge.net:/home/frs/project/"$project"/internal/pool/

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $0 No error detected. (benchmark: $benchmark_took_time)${reset}"
