#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## {{ usage

## From Whonix main source code folder.

## wheezy - tested
#cd build-steps.d
#ln -s ../packages/whonix-developer-meta-files/debug-steps/1400_backup-raw-after-grml-debootstrap ./
#cd ..
#./build-steps.d/1400_backup-raw-after-grml-debootstrap

## jessie - untested
#ln -r -s ./packages/whonix-developer-meta-files/debug-steps/1400_backup-raw-after-grml-debootstrap ./build-steps.d/
#./build-steps.d/1400_backup-raw-after-grml-debootstrap

## }}

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

root_check

backup-raw-after-grml-debootstrap() {
   errorhandlersetup "errorhandlergeneral" ERR INT TERM

   ## If whonix_build is run with --fast1 switch.
   if [ "$WHONIX_BUILD_FAST1" = "1" ]; then
      echo "${bold}${cyan}INFO: run with --fast1 switch, skipping $BASH_SOURCE. ${reset}"
      exit 0
   fi

   cp "$binary_image_raw" "$WHONIX_BINARY/$VMNAME-$anon_dist_build_version-backup-after-grml-debootstrap.raw"
   chown --recursive "$user_name:$user_name" "$WHONIX_BINARY"/
}

if [ "$ANON_BUILD_INSTALL_TO_ROOT" = "1" ]; then
   true "${green}INFO: Skipping $BASH_SOURCE, because ANON_BUILD_INSTALL_TO_ROOT is set to 1.${reset}"
else
   true "${bold}${under}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
   if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
      backup-raw-after-grml-debootstrap
   elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
      backup-raw-after-grml-debootstrap
   elif [ "$WHONIX_BUILD_CUSTOM_WORKSTATION" = "1" ]; then
      true "${cyan}INFO: Skipping backup-raw-after-grml-debootstrap for $VMNAME.${reset}"
   else
      error "ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!"
   fi
   benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}${under}INFO: End of: $BASH_SOURCE ${1+"$@"} | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
fi
