#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source colors
source variables

backup-raw-after-package-install() {
   ## If whonix_build is run with --fast2 switch.
   if [ "$WHONIX_BUILD_FAST2" = "1" ]; then
      echo "${bold}${cyan}INFO: run with --fast2 switch, skipping $BASH_SOURCE. ${reset}"
      exit 0
   fi

   cp "$binary_image_raw" "$WHONIX_BINARY/$VMNAME-$anon_dist_build_version-backup-after-package-install.raw"
   chown --recursive "$user_name:$user_name" "$WHONIX_BINARY"/
}

main() {
   if [ "$ANON_BUILD_INSTALL_TO_ROOT" = "1" ]; then
      true "${green}INFO: Skipping $BASH_SOURCE, because ANON_BUILD_INSTALL_TO_ROOT is set to 1.${reset}"
   elif [ "$WHONIX_BUILD_QUBES" = "true" ]; then
      true "${green}INFO: Skipping $BASH_SOURCE, because WHONIX_BUILD_QUBES is set to true.${reset}"
   else
      if [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
         backup-raw-after-package-install
      elif [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
         backup-raw-after-package-install
      elif [ "$WHONIX_BUILD_CUSTOM_WORKSTATION" = "1" ]; then
         true "${cyan}INFO: Skipping backup-raw-after-package-install for $VMNAME.${reset}"
      else
         error "ERROR: Neither WHONIX_BUILD_GATEWAY nor WHONIX_BUILD_WORKSTATION is set to 1. Please report this bug!"
      fi
   fi
}

main ${1+"$@"}
