#!/bin/bash
# diffp: compare two package builds
# Copyright (C) 2013 Lunar <lunar@debian.org>
# Licensed under WTFPL http://www.wtfpl.net/txt/copying/
#
# Depends: bash, binutils, unzip

CHANGES_A="$1"
CHANGES_B="$2"

trim_diff() {
        grep -Ev '^(@@ |--- |\+\+\+ )'
}

get_ops() {
        local file="$1"

        case "$file" in
            */bin/*|*/sbin/*)
                case "$(ar p $PACKAGE_A data.tar.xz | tar -JxOf - $file | file -)" in
                    *ELF*)
                        echo "readelf -a FILE"
                        echo "readelf -w FILE"
                        echo "objdump -d FILE"
                        ;;
                esac
                ;;
            *.so|*.so.[0-9]*)
                echo "readelf -a FILE"
                echo "readelf -w FILE"
                echo "objdump -d FILE"
                ;;
            *.a)
                echo "ar tv FILE"
                ;;
            *.zip|*.jar)
                echo "unzip -lv FILE"
                ;;
            *.gz)
                echo "file FILE"
                echo "zcat FILE"
                ;;
        esac
}

diffc() {
        local diff

        diff="$(diff -u0 <(echo "$@" | sed -e "s,PACKAGE,$PACKAGE_A," | sh) \
                 <(echo "$@" | sed -e "s,PACKAGE,$PACKAGE_B," | sh))"
        [ "$diff" ] || return 0
        echo "$diff" | trim_diff
        return 1
}

paste <(dcmd "$CHANGES_A" | sort | grep '\.deb$') <(dcmd "$CHANGES_B" | sort | grep '\.deb$') | while read PACKAGE_A PACKAGE_B; do
        PACKAGE="$(basename "$PACKAGE_A")"
        if [ "$PACKAGE" != "$(basename "$PACKAGE_B")" ]; then
                echo "$PACKAGE_A and $PACKAGE_B does not match. Something is wrong."
                exit 1
        fi
        echo "***** $PACKAGE"

        diffc "sha1sum < PACKAGE | sed -e 's,-$,$PACKAGE,'" && continue

        diffc 'ar tv PACKAGE' && continue

        MISMATCH=
        for file in debian-binary control.tar.gz data.tar.xz; do
                if diffc "ar p PACKAGE $file | sha1sum | sed -e s/-$/$file/"; then
                        MISMATCH=1
                fi
        done
        [ "$MISMATCH" ] || continue

        echo "===== control.tar.gz"

        diffc 'ar p PACKAGE control.tar.gz | tar -ztvf -'
        ar p $PACKAGE_A control.tar.gz | tar -zvtf - | grep '^-' | while read flags user size date time file; do
                echo "----- $file"
                diffc "ar p PACKAGE control.tar.gz | tar -zxOf - $file"
        done

        echo "===== data.tar.xz"
        if ar p "$PACKAGE_A" control.tar.gz | tar -ztf - ./md5sums; then
                FILES="$(diffc "ar p PACKAGE control.tar.gz | tar -zxOf - ./md5sums" | awk '/^-/ { print "./" $2 }')"
        else
                FILES="$(ar p $PACKAGE_A data.tar.xz | tar -Jvtf - | awk '/^-/ { print $6 }')"
        fi
        diffc 'ar p PACKAGE data.tar.xz | tar -Jtvf -'
        echo "$FILES" | while read file; do
                echo "----- $file"
                diffc "ar p PACKAGE data.tar.xz | tar -JxOf - $file" |
                    sed -e "s,Binary files [^ ]* and [^ ]* differ,Binary file $file differ,"

                OPS="$(get_ops "$file")"
                [ "$OPS" ] || continue

                TMP_A=$(mktemp)
                TMP_B=$(mktemp)
                ar p $PACKAGE_A data.tar.xz | tar -JxOf - $file > "$TMP_A"
                ar p $PACKAGE_B data.tar.xz | tar -JxOf - $file > "$TMP_B"
                echo "$OPS" | while read op; do
                        diff -u0 <(echo "$op" | sed -e "s,FILE,$TMP_A," | sh | sed -e "s,$TMP_A,$file,g") \
                                 <(echo "$op" | sed -e "s,FILE,$TMP_B," | sh | sed -e "s,$TMP_B,$file,g") | trim_diff
                done
                rm -f "$TMP_A" "$TMP_B"
        done
done
