#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

download_sources() {
   trap "error_handler_general" ERR INT TERM

   "$MYDIR"/mount-raw
   "$MYDIR"/prevent-daemons-from-starting

   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"
   "$MYDIR"/chroot-raw

   $CHROOT "/usr/share/whonix/whonix_download_sources"
   sync

   "$MYDIR"/unchroot-raw
   "$MYDIR"/unprevent-daemons-from-starting
   "$MYDIR"/unmount-raw
}

move_sources() {
   trap "error_handler_general" ERR INT TERM

   "$MYDIR"/mount-raw
   "$MYDIR"/prevent-daemons-from-starting

   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"
   "$MYDIR"/chroot-raw

   mkdir --parents ""$WHONIX_BINARY"/sources/"$VMNAME""

   mv "$CHROOT_FOLDER/usr/share/whonix/sources/*" ""$WHONIX_BINARY"/sources/"$VMNAME"/"

   #rm -r "$CHROOT_FOLDER/usr/share/whonix/sources/"

   chown --recursive "$user_name:$user_name" ""$WHONIX_BINARY"/"

   "$MYDIR"/unchroot-raw
   "$MYDIR"/unprevent-daemons-from-starting
   "$MYDIR"/unmount-raw
}

true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"

download_sources
move_sources

benchmark_time_end ## sets benchmark_took_time (implemented in help-steps/pre)
true "${bold}INFO: End of: $BASH_SOURCE No error detected. (benchmark: $benchmark_took_time)${reset}"
