#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "Currently running script: $0 ${1+"$@"}"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../Whonix/help-steps/pre
source ../../Whonix/help-steps/variables

download_sources() {
   trap "error_handler_general" ERR INT TERM

   "$MYDIR"/mount-img
   "$MYDIR"/prevent-daemons-from-starting

   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"
   "$MYDIR"/chroot-img

   $CHROOT "/usr/share/whonix/whonix_download_sources"
   sync

   "$MYDIR"/unchroot-img
   "$MYDIR"/unprevent-daemons-from-starting
   "$MYDIR"/unmount-img
}

move_sources() {
   trap "error_handler_general" ERR INT TERM

   "$MYDIR"/mount-img
   "$MYDIR"/prevent-daemons-from-starting

   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"
   "$MYDIR"/chroot-img

   mkdir --parents ""$WHONIX_BINARY"/sources/"$VMNAME""

   mv "$CHROOT_FOLDER/usr/share/whonix/sources/*" ""$WHONIX_BINARY"/sources/"$VMNAME"/"

   #rm -r "$CHROOT_FOLDER/usr/share/whonix/sources/"

   chown --recursive "$user_name:$user_name" ""$WHONIX_BINARY"/"

   "$MYDIR"/unchroot-img
   "$MYDIR"/unprevent-daemons-from-starting
   "$MYDIR"/unmount-img
}

true "${bold}INFO: Currently running script: $0 ${1+"$@"}${reset}"

download_sources
move_sources

true "${bold}INFO: End of: $0 No error detected.${reset}"
