#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

true "Currently running script: $0"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"
cd ..
cd help-steps

source pre
source variables

error_handler_interactive-chroot-img-shell() {
   trap "error_handler_interactive-img" ERR INT TERM

   echo "${green}INFO${reset}: Exited (1) interactive shell."
   sync
}

error_handler_interactive-chroot-img() {
   echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
Unchrooting.. Unpreventing daemons from starting... Unmounting img...
"

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-img
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-img

   echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $0: | caller: $(caller)${reset}
"

   exit 1
}

interactive-chroot-img() {
   trap "error_handler_interactive-chroot-img" ERR INT TERM

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/mount-img

   echo "${cyan}INFO: Trying to prevent daemons from starting, if /usr/sbin/ folder already exist (will fail open, if not)...${reset}"

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/prevent-daemons-from-starting || true

   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/chroot-img

   sync

   ## Sanity tests.
   $CHROOT mount
   $CHROOT $update_grub_bin -v
   $CHROOT sync

   sync

   echo "${cyan}INFO: Trying to make local APT repository available inside chroot, if already available (will fail open, if not)...${reset}"

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/create-local-temp-apt-repo || true

   ## Debugging.
   $CHROOT apt-key finger  || true

   ## Implemented in help-steps/pre.
   maybe_enable_apt_cache

   sync

   ## Info.
   echo "${cyan}INFO: Entering interactive shell...${reset}"
   echo "${cyan}Recommendation: check /home/user if you are really inside the image and not on your host system."
   echo "    When you are done, do not forget to leave the shell using: exit 0${reset}"

   ## Run interactive shell.
   trap "error_handler_interactive-chroot-img-shell" ERR INT TERM
   $CHROOT "/bin/bash"

   echo "${green}INFO: Exited (0) interactive shell.${reset}"

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/remove-local-temp-apt-repo

   $CHROOT sync
   sync

   ## Implemented in help-steps/pre.
   disable_apt_cache

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unchroot-img
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unprevent-daemons-from-starting
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER"/unmount-img

   sync

   echo "${green}INFO: Terminated interactive chroot without any errors.${reset}"
}

true "${bold}INFO: Currently running script: $0${reset}"
interactive-chroot-img
true "${bold}INFO: End of: $0 No error detected.${reset}"
