#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

main() {
   trap "errorhandlerunchrootunpreventunmount" ERR INT TERM

   ## Lockfile for whonixcheck.
   touch "/run/package_manager_lock"

   sync

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER/mount-raw"
   #"$WHONIX_SOURCE_HELP_STEPS_FOLDER/prevent-daemons-from-starting"

   export WHONIX_CHROOT_MOUNT_RESOLV_CONF="0"
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER/chroot-raw"

   sync

   ## Sanity test.
   $CHROOT sync

   sync

   ## Backup exiting /etc/apt/sources.list, might be useful for bare metal users.
   ## No longer required, we are no longer shipping /etc/apt/sources.list.
   #if [ -f "$CHROOT_FOLDER/etc/apt/sources.list" ]; then
      #cp --no-clobber --recursive --preserve "$CHROOT_FOLDER/etc/apt/sources.list" "$CHROOT_FOLDER/etc/apt/sources.list.backup"
   #fi

   ## We have to manually fix /etc/apt/sources.list, because the list which comes with
   ## grml-debootstrap is incomplete (does not complain debian security repository) and points to 127.0.0.1.

   ## This file doesn't include Whonix's APT repository.
   cp "$WHONIX_SOURCE_FOLDER/packages/anon-apt-sources-list/etc/apt/sources.list.d/debian.list" "$CHROOT_FOLDER/etc/apt/sources.list.d/"

   ## Not using any /etc/apt/preferences.d snippets at the moment.
   #cp "$WHONIX_SOURCE_FOLDER/packages/...todo.../etc/apt/preferences.d/"* "$CHROOT_FOLDER/etc/apt/preferences.d/"

   ## Not using any important /etc/apt/apt.conf.d snippets at the moment.
   #cp "$WHONIX_SOURCE_FOLDER/packages/...todo.../etc/apt/apt.conf.d/"* "$CHROOT_FOLDER/etc/apt/apt.conf.d/"

   sync

   ## Upgrade from regular repository.
   ## Out commented. Instructions leave that to the user. This is better,
   ## because this script would fail if some repository would not be reachable,
   ## such as torproject's Tor 0.2.4 apt repository.
   #$CHROOT apt-get ${APTGETOPT[@]} update
   #$CHROOT apt-get ${APTGETOPT[@]} --yes dist-upgrade

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER/create-local-temp-apt-repo"

   ## Check if we are running on a Whonix-Gateway.
   if [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
      true 'INFO: We are running on a Whonix-Gateway, setting UWT_DEV_PASSTHROUGH="0", ok.'

      ## Someone trying to update Whonix-Gateway from source code. By default,
      ## export UWT_DEV_PASSTHROUGH="1" has been set in help-steps/variables.
      ## This won't work from within an installed Whonix-Gateway, because it by
      ## design does not have functional system DNS.
      export UWT_DEV_PASSTHROUGH="0"
   fi

   ## Debugging.
   $CHROOT apt-key finger

   ## Reading [apt repository containing snapshot.debian.org and] local repository containing Whonix's packages.
   $CHROOT apt-get ${APTGETOPT[@]} $apt_sourcelist_empty $apt_sourceparts -o APT::Get::List-Cleanup="0" update

   if [ "$WHONIX_BUILD_FLAVOR" = "whonix-gateway-kde" ]; then
      $CHROOT apt-get ${APTGETOPT[@]} $apt_sourcelist_empty $apt_sourceparts --yes install \
         whonix-gateway-packages-dependencies-pre \
         anon-shared-packages-dependencies \
         anon-shared-packages-recommended \
         anon-shared-desktop \
         anon-shared-desktop-kde \
         anon-shared-kde-accessibility \
         whonix-shared-packages-dependencies \
         whonix-shared-packages-recommended \
         anon-gateway-packages-dependencies \
         anon-gateway-packages-recommended \
         whonix-gateway-packages-dependencies \
         whonix-gateway-packages-recommended
   elif [ "$WHONIX_BUILD_FLAVOR" = "whonix-workstation-kde" ]; then
      $CHROOT apt-get ${APTGETOPT[@]} $apt_sourcelist_empty $apt_sourceparts --yes install \
         whonix-workstation-packages-dependencies-pre \
         anon-shared-packages-dependencies \
         anon-shared-packages-recommended \
         anon-shared-desktop \
         anon-shared-desktop-kde \
         anon-shared-kde-accessibility \
         whonix-shared-packages-dependencies \
         whonix-shared-packages-recommended \
         anon-workstation-packages-dependencies \
         anon-workstation-packages-recommended \
         whonix-workstation-packages-dependencies \
         whonix-workstation-packages-recommended
   else
      local MSG="${bold}${red}$BASH_SOURCE ERROR: VMNAME is neither Whonix-Gateway nor Whonix-Workstation. Please report this bug! ${reset}"
      error "$MSG"
   fi

   ## Upgrade Whonix Debian Packages.
   $CHROOT apt-get ${APTGETOPT[@]} $apt_sourcelist_empty $apt_sourceparts --yes dist-upgrade

   #$CHROOT apt-get ${APTGETOPT[@]} $apt_sourcelist_empty $apt_sourceparts -f install

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER/remove-local-temp-apt-repo"

   ## Forget about local repository containing Whonix's packages.
   $CHROOT apt-get --no-download --list-cleanup update

   $CHROOT sync
   sync

   ## Remove lockfile for whonixcheck.
   rm --force "/run/package_manager_lock"

   "$WHONIX_SOURCE_HELP_STEPS_FOLDER/unchroot-raw"
   #"$WHONIX_SOURCE_HELP_STEPS_FOLDER/unprevent-daemons-from-starting"
   "$WHONIX_SOURCE_HELP_STEPS_FOLDER/unmount-raw"

   sync
}

main "$@"
