#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

error_handler_mount-vdi() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $BASH_SOURCE: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

mount_vdi() {
   trap "error_handler_mount-vdi" ERR INT TERM

   sync

   ## Ensure powered is off. Otherwise disk corruption is at high risk.
   sudo -u "$user_name" VBoxManage controlvm "$VMNAME" poweroff || true
   sync

   ## Find name of .vdi file. New:
   local vdi_file
   vdi_file="$(find "$HOMEVAR/VirtualBox VMs/$VMNAME/"*".vdi")"
   ## example result: "$HOMEVAR"/VirtualBox VMs/whonix-Gateway/whonix-Gateway-disk1.vdi
   ## For debugging it's useful to clone a VM, where only the operating system has been installed,
   ## before running the script or before copying into it.
   ## When restoring the VMClone to VM, the VDI may have another name.

   ## Folder has to exist to mount the image.
   mkdir --parents "$CHROOT_FOLDER"
   sync

   guestmount -o allow_other -a "$vdi_file" -m /dev/sda1 "$CHROOT_FOLDER"
   sync
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping script, because BARE_METAL=1: $BASH_SOURCE${reset}"
   exit 0
else
   true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
   mount_vdi
   benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
fi
