#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

## disable cmd line parser, since not needed
export whonix_build_one_parsed="1"
export VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

#target_vm="sys-whonix-dev"
#target_vm="sys-whonix"

#target_vm="anon-whonix-dev"
#target_vm="anon-whonix"

#target_vm="whonix-ws-dev"
#target_vm="whonix-ws"

#target_vm="whonix-gw-dev"
#target_vm="whonix-gw"

if [ "$target_vm" = "" ]; then
   error_ "$target_vm must not be empty!"
fi

source_vm="$(qubesdb-read /name)"

## Get rid of huge .git folder.
rm -r -f "$binary_build_folder_dist/aptrepo_temp_copy/"
sudo $SUDO_OPTS mkdir -p "$binary_build_folder_dist/aptrepo_temp_copy"
sudo $SUDO_OPTS cp -r "$binary_build_folder_dist/aptrepo_remote/dists" "$binary_build_folder_dist/aptrepo_temp_copy/dists"
sudo $SUDO_OPTS cp -r "$binary_build_folder_dist/aptrepo_remote/pool" "$binary_build_folder_dist/aptrepo_temp_copy/pool"

echo "deb [trusted=yes] file:/var/cache/aptrepo_temp_copy $dist_build_apt_codename main" > "$binary_build_folder_dist/whonix_repo_temp.list"
cat "$binary_build_folder_dist/whonix_repo_temp.list"

qvm-run "$target_vm" "rm -r -f /home/user/QubesIncoming/$source_vm/aptrepo_temp_copy"
qvm-run "$target_vm" "rm -f /home/user/QubesIncoming/$source_vm/whonix_repo_temp.list"
qvm-run "$target_vm" "sudo rm -f /etc/apt/sources.list.d/whonix_repo_temp.list"

qvm-copy-to-vm "$target_vm" "$binary_build_folder_dist/whonix_repo_temp.list"
qvm-copy-to-vm "$target_vm" "$binary_build_folder_dist/aptrepo_temp_copy/"

qvm-run "$target_vm" "sudo mv /home/user/QubesIncoming/$source_vm/whonix_repo_temp.list /etc/apt/sources.list.d/whonix_repo_temp.list"

qvm-run "$target_vm" "sudo rm -r -f /var/cache/aptrepo_temp_copy"
qvm-run "$target_vm" "sudo cp -r /home/user/QubesIncoming/$source_vm/aptrepo_temp_copy /var/cache/aptrepo_temp_copy"
qvm-run "$target_vm" "sudo chown -R _apt /var/cache/aptrepo_temp_copy"

qvm-run "$target_vm" "sudo apt-get update"

true "INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected."
