#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## usage:
## ./debug-steps/reprepro-wrapper listmatched local "*"

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE${1+"$@"}"

whonix_build_one_parsed="1"
VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

main() {
   reprepro \
      $WHONIX_BUILD_REPREPRO_SIGNING_OPTIONS \
      $WHONIX_BUILD_REPREPRO_FOLDER_OPTIONS \
      ${1+"$@"}
   true
}

main ${1+"$@"}
