#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## usage:
## ./debug-steps/reprepro-wrapper listmatched local "*"

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

whonix_build_one_parsed="1"
VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

main() {
   reprepro_exit_code="0"
   reprepro_output="$(reprepro \
      $WHONIX_BUILD_REPREPRO_SIGNING_OPTIONS \
      $WHONIX_BUILD_REPREPRO_FOLDER_OPTIONS \
      "$@" 2>&1)" || { reprepro_exit_code="$?" ; true; };

   if echo "$reprepro_output" | grep "is already registered with different checksums!" ; then
      return 0
   fi

   return "$reprepro_exit_code"
}

set_WHONIX_BUILD_REPREPRO_FOLDER_OPTIONS
main "$@"
