#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## usage:
## ./debug-steps/reprepro-wrapper listmatched local "*"

set -x
set -e

true "INFO: Currently running script: $BASH_SOURCE $@"

dist_build_one_parsed="1"
VMNAME="internalrun"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../../help-steps/pre
source ../../../../help-steps/colors
source ../../../../help-steps/variables

main() {
   reprepro_exit_code="0"
   reprepro_output="$(reprepro \
      $dist_build_reprepro_signing_options \
      $dist_build_reprepro_folder_options \
      "$@" 2>&1)" \
      || { reprepro_exit_code="$?" ; true; };

   if echo "$reprepro_output" | grep "is already registered with different checksums!" ; then
      return 0
   fi

   return "$reprepro_exit_code"
}

set_dist_build_reprepro_folder_options
main "$@"
