#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Small script for Travis CI.

set -x

true "INFO: Currently running script: $0"

set -o pipefail

error_handler_travis() {
   exit 1
}

trap "error_handler_travis" ERR

true "INFO $0: Script running as user: $(logname)"

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

## Back to whonix-developer-meta-files folder.
cd ..

## Back to parent folder.
cd ..

## Get into Whonix folder.
cd Whonix

WHONIX_BUILD_PARSED="1"
VMNAME="internalrun"

source ./help-steps/variables

## Debugging.
ls -la
ls -la ./debian/

## {{ minimal

minimal() {
   local config_folder="/etc/whonix_buildconfig.d"

   mkdir --parents "$config_folder"

echo '\
## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

whonix_build_script_whonix_package+=" whonix-shared-desktop "
whonix_build_script_whonix_package+=" whonix-shared-desktop-kde "
whonix_build_script_whonix_package+=" whonix-shared-kde-accessibility "
' | sudo tee "/etc/whonix_buildconfig.d/50_terminal_only_gateway" > /dev/null

echo '\
## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

whonix_build_script_whonix_package+=" whonix-shared-packages-recommended "
whonix_build_script_whonix_package+=" whonix-gateway-packages-recommended "
whonix_build_script_whonix_package+=" whonix-workstation-packages-recommended "
whonix_build_script_whonix_package+=" whonix-workstation-default-applications "
' | sudo tee "/etc/whonix_buildconfig.d/50_minimal" > /dev/null

echo '\
## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## NOTE: It is impossible to create 64 bit builds on 32 bit hosts.
##       (This is a limitation of (grml-)debootstrap.)

## i386 is the default target architecture,
## if WHONIX_TARGET_ARCH variable is not set or empty.
#export WHONIX_TARGET_ARCH="i386"

## Interesting target architecture for custom builds: 64 bit
## Despite its name, works on AMD and Intel.
export WHONIX_TARGET_ARCH="amd64"

## Also interesting target architectures for custom builds: Kernel of FreeBSD
## Will not work out of the box for Whonix-Gateway, because Whonix Firewall
## is based on iptables (Linux) and the FreeBSD does not support iptables,
## its firewall is pf. The Whonix iptables rules would have to be rewritten in pf.
#export WHONIX_TARGET_ARCH="kfreebsd-amd64"
#export WHONIX_TARGET_ARCH="kfreebsd-i386"
' | sudo tee "/etc/whonix_buildconfig.d/50_target_arch" > /dev/null

## Currently out commented, because apt-cacher-ng does not like our sourceforge
## APT repository.
##
#echo '## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Do use or do not use Whonix APT Repository.
## 0: do use.
## 1: do not use.
#export WHONIX_APT_REPOSITORY_DISTRUST_ENV="0"

## Which version of Whonix you want to use.
## Defaults to stable.
#export WHONIX_APT_REPOSITORY_DISTRIBUTION_CONFIG="stable"
#export WHONIX_APT_REPOSITORY_DISTRIBUTION_CONFIG="testers"
#export WHONIX_APT_REPOSITORY_DISTRIBUTION_CONFIG="developers"

## Technical comment:
## Using export so the /usr/bin/whonix_repository tool and
## /usr/share/whonix/postinst.d/70_whonix_apt_key can read it.
#' | sudo tee "/etc/whonix_buildconfig.d/50_whonix_apt_repository" > /dev/null

   cat "$config_folder"/*
}

## }}

## {{ Build physically isolated machine.

if [ "$TRAVIS_BRANCH" = "gateway-travis" ]; then
   sudo -E ./whonix_build --tor-gateway --bare-metal --build
elif [ "$TRAVIS_BRANCH" = "minimal-gateway-travis" ]; then
   minimal
   sudo -E ./whonix_build --tor-gateway --bare-metal --build
elif [ "$TRAVIS_BRANCH" = "pkg-only-gateway-travis" ]; then
   sudo -E ./build-steps.d/1100_prepare-build-machine
   ./build-steps.d/1200_create-debian-packages
   sudo -E "$whonix_dev_meta_files_folder/debug-steps/locally-upgrade-whonix-debian-packages" --bare-metal --tor-gateway
elif [ "$TRAVIS_BRANCH" = "minimal-workstation-travis" ]; then
   minimal
   sudo -E ./whonix_build --tor-workstation --bare-metal --build
elif [ "$TRAVIS_BRANCH" = "workstation-travis" ]; then
   sudo -E ./whonix_build --tor-workstation --bare-metal --build
elif [ "$TRAVIS_BRANCH" = "pkg-only-workstation-travis" ]; then
   sudo -E ./build-steps.d/1100_prepare-build-machine
   ./build-steps.d/1200_create-debian-packages
   sudo -E "$whonix_dev_meta_files_folder/debug-steps/locally-upgrade-whonix-debian-packages" --bare-metal --tor-workstation
else
   error "Unknown $TRAVIS_BRANCH branch, check $0."
fi

## }}

## Test Whonix First Run Initializer.
./whonix_shared/usr/lib/whonix/first_run_initializer

## Cleanup, so we can create a dummy update package to test the upgrade
## process. (See if re-running all scripts is supported.)
make clean

## Commit a dummy change.
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
temp="dummy_file"
touch "$temp"
git add "$temp"
git commit -m "dummy commit"

## Create a new dummy tag
git tag 101 -m "."

## Debugging.
ls -la ./debian/

## {{ Test the upgrading from local repository process.

export whonix_build_closest_git_tag="101"

if [ "$TRAVIS_BRANCH" = "gateway-travis" ]; then
   ./build-steps.d/1200_create-debian-packages
   sudo -E "$whonix_dev_meta_files_folder/debug-steps/locally-upgrade-whonix-debian-packages" --bare-metal --tor-gateway
elif [ "$TRAVIS_BRANCH" = "minimal-gateway-travis" ]; then
   ./build-steps.d/1200_create-debian-packages
   sudo -E "$whonix_dev_meta_files_folder/debug-steps/locally-upgrade-whonix-debian-packages" --bare-metal --tor-gateway
elif [ "$TRAVIS_BRANCH" = "pkg-only-gateway-travis" ]; then
   ./build-steps.d/1200_create-debian-packages
   sudo -E "$whonix_dev_meta_files_folder/debug-steps/locally-upgrade-whonix-debian-packages" --bare-metal --tor-gateway
elif [ "$TRAVIS_BRANCH" = "minimal-workstation-travis" ]; then
   ./build-steps.d/1200_create-debian-packages
   sudo -E "$whonix_dev_meta_files_folder/debug-steps/locally-upgrade-whonix-debian-packages" --bare-metal --tor-workstation
elif [ "$TRAVIS_BRANCH" = "workstation-travis" ]; then
   ./build-steps.d/1200_create-debian-packages
   sudo -E "$whonix_dev_meta_files_folder/debug-steps/locally-upgrade-whonix-debian-packages" --bare-metal --tor-workstation
elif [ "$TRAVIS_BRANCH" = "pkg-only-workstation-travis" ]; then
   ./build-steps.d/1200_create-debian-packages
   sudo -E "$whonix_dev_meta_files_folder/debug-steps/locally-upgrade-whonix-debian-packages" --bare-metal --tor-workstation
else
   error "Unknown $TRAVIS_BRANCH branch, check $0."
fi

## }}

## Cleanup.
make clean

## Debugging.
ls -la ../
ls -la /home/travis/whonix_binary/
ls -la /home/travis/whonix_binary/*.report

true "INFO $0: Showing report..."
cat /home/travis/whonix_binary/*.report
true "INFO $0: Done, showed report."

true "INFO $0: Executing Run Initializer Gui..."
/usr/lib/whonix/first_run_initializer_gui
true "INFO $0: Executed First Run Initializer Gui."

service backgroundd start || true
service timesanitycheck start || true
service bootclockrandomization start || true
service timesyncd start || true
service msgcollector start || true
service sdwdate start || true
service whonixcheckd start || true

true "INFO $0: Executing whonixcheck..."
sudo -E -u travis bash -x whonixcheck || true
true "INFO $0: Executed whonixcheck."

true "INFO $0: Executing timesync..."
sudo -E -u travis bash -x timesync || true
true "INFO $0: Executed timesync."

## {{ Do not try to reboot Travis CI!

## Do not do this!!!
## Otherwise you'll run into...
## "I'm sorry but there was an error with the connection to the VM.
## Your job will be requeued shortly."
## reboot

## }}

## End.
true "INFO: End of: $0 No error detected."
