#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

errorhandlerunmount-vdi() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $BASH_SOURCE: | caller: $(caller)${reset}
"
   exit 1
}

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

source ../../../help-steps/pre
source ../../../help-steps/colors
source ../../../help-steps/variables

unmount_vdi() {
   trap "errorhandlerunmount-vdi" ERR INT TERM

   sync

   local command_v_exit_code="0"
   command -v guestunmount >/dev/null || { command_v_exit_code="$?" ; true; };

   if [ "$command_v_exit_code" = "0" ]; then
      true "${bold}${cyan}INFO: guestunmount available, using it, ok... ${reset}"
      guestunmount "$CHROOT_FOLDER"
   else
      ## guestunmount is not available in Debian Wheezy. Only since Debian Jessie.
      true "${bold}${cyan}INFO: guestunmount not available, using \"fusermount -u\" instead, ok... ${reset}"
      fusermount -u "$CHROOT_FOLDER"
   fi
   sync

   ## Delete temporary folder.
   ## It did not contain anything. It was only a mount point.
   rm -r "$CHROOT_FOLDER"
   sync
}

if [ "$BARE_METAL" = "1" ]; then
   true "${green}INFO: Skipping script, because BARE_METAL=1: $BASH_SOURCE${reset}"
   exit 0
else
   true "${bold}INFO: Currently running script: $BASH_SOURCE ${1+"$@"}${reset}"
   unmount_vdi
   benchmarktimeend ## sets benchmark_took_time (implemented in help-steps/pre)
   true "${bold}INFO: End of: $BASH_SOURCE | $whonix_build_error_counter error(s) detected. (benchmark: $benchmark_took_time)${reset}"
fi
