#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

build_all_error_handler() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $BASH_SOURCE: | caller: $(caller)${reset}
"
   exit 1
}

trap "build_all_error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"

cd ..
cd ..
cd ..

rm --recursive --force "/home/$SUDO_USER/whonix_binary"
rm --recursive --force "/home/$SUDO_USER/whonix_binary_first"
rm --recursive --force "/home/$SUDO_USER/whonix_binary_second"

./whonix_build --tor-gateway -- --clean --target virtualbox ${1+"$@"}
./whonix_build --tor-workstation -- --clean --target virtualbox ${1+"$@"}
./whonix_build --tor-custom-workstation -- --clean --target virtualbox ${1+"$@"}

./whonix_build --tor-gateway -- --build --report true --target virtualbox ${1+"$@"}
./whonix_build --tor-workstation -- --build --report true --target virtualbox ${1+"$@"}
./whonix_build --tor-custom-workstation -- --build --report true --target virtualbox ${1+"$@"}

mv "/home/$SUDO_USER/whonix_binary" "/home/$SUDO_USER/whonix_binary_first"

./whonix_build --tor-gateway -- --clean --target virtualbox ${1+"$@"}
./whonix_build --tor-workstation -- --clean --target virtualbox ${1+"$@"}
./whonix_build --tor-custom-workstation -- --clean --target virtualbox ${1+"$@"}

./whonix_build --tor-gateway -- --build --report true --target virtualbox ${1+"$@"}
./whonix_build --tor-workstation -- --build --report true --target virtualbox ${1+"$@"}
./whonix_build --tor-custom-workstation -- --build --report true --target virtualbox ${1+"$@"}

mv "/home/$SUDO_USER/whonix_binary" "/home/$SUDO_USER/whonix_binary_second"

true "meld /home/$SUDO_USER/whonix_binary_first/Whonix-Gateway-*.report /home/$SUDO_USER/whonix_binary_second/Whonix-Gateway-*.report"
true "meld /home/$SUDO_USER/whonix_binary_first/Whonix-Workstation-*.report /home/$SUDO_USER/whonix_binary_second/Whonix-Workstation-*.report"
