#!/bin/bash

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

build_all_error_handler() {
   : echo "
${red}${bold}BASH_COMMAND${reset}: $BASH_COMMAND
${red}${bold}ERROR $BASH_SOURCE: | caller: $(caller)${reset}
"
   exit 1
}

trap "build_all_error_handler" ERR

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$MYDIR"

cd ..
cd ..
cd ..

rm --recursive --force "/home/$SUDO_USER/derivative-binary"
rm --recursive --force "/home/$SUDO_USER/derivative-binary_first"
rm --recursive --force "/home/$SUDO_USER/derivative-binary_second"

./derivative-maker --tor-gateway            -- --clean --target virtualbox "$@"
./derivative-maker --tor-workstation        -- --clean --target virtualbox "$@"
./derivative-maker --tor-custom-workstation -- --clean --target virtualbox "$@"

./derivative-maker --tor-gateway            -- --build --target virtualbox --report true "$@"
./derivative-maker --tor-workstation        -- --build --target virtualbox --report true "$@"
./derivative-maker --tor-custom-workstation -- --build --target virtualbox --report true "$@"

mv "/home/$SUDO_USER/derivative-binary" "/home/$SUDO_USER/derivative-binary_first"

./derivative-maker --tor-gateway            -- --clean --target virtualbox "$@"
./derivative-maker --tor-workstation        -- --clean --target virtualbox "$@"
./derivative-maker --tor-custom-workstation -- --clean --target virtualbox "$@"

./derivative-maker --tor-gateway            -- --build --target virtualbox --report true "$@"
./derivative-maker --tor-workstation        -- --build --target virtualbox --report true "$@"
./derivative-maker --tor-custom-workstation -- --build --target virtualbox --report true "$@"

mv "/home/$SUDO_USER/derivative-binary" "/home/$SUDO_USER/derivative-binary_second"

true "meld /home/$SUDO_USER/derivative-binary_first/Whonix-Gateway-*.report /home/$SUDO_USER/derivative-binary_second/Whonix-Gateway-*.report"
true "meld /home/$SUDO_USER/derivative-binary_first/Whonix-Workstation-*.report /home/$SUDO_USER/derivative-binary_second/Whonix-Workstation-*.report"
